import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { PrismaClient } from '@founder-os/db';
import { JobRepository, WorkerRepository } from '@founder-os/db';

const db=new PrismaClient();
const marker=`v109-process-${Date.now()}-${Math.random().toString(36).slice(2)}`;
async function cleanup(orgId:string){await db.auditEvent.deleteMany({where:{organizationId:orgId}});await db.approval.deleteMany({where:{organizationId:orgId}});await db.checkpoint.deleteMany({where:{organizationId:orgId}});await db.job.deleteMany({where:{organizationId:orgId}});await db.workflow.deleteMany({where:{organizationId:orgId}});await db.workerCredential.deleteMany({where:{worker:{organizationId:orgId}}});await db.worker.deleteMany({where:{organizationId:orgId}});await db.organization.delete({where:{id:orgId}})}
test.after(async()=>db.$disconnect());

test('V1.09 real process interruption leaves durable lease state and recovery resumes it',async(t)=>{if(!process.env.DATABASE_URL){t.skip('DATABASE_URL is required');return}const org=await db.organization.create({data:{name:marker}});try{const wr=new WorkerRepository(db),w=await wr.create({organizationId:org.id,name:'process-worker',type:'test',capabilities:['internal.execute'],credential:'process-worker-credential-v109-123456789'},{organizationId:org.id,actorType:'SYSTEM',eventType:'worker.created',action:'test',result:'SUCCESS'}),job=await db.job.create({data:{organizationId:org.id,status:'QUEUED',resumableState:{},metadata:{}}}),repo=new JobRepository(db);const child=spawn(process.execPath,['--import','tsx','apps/worker/fixtures/v109-process-worker.ts',org.id,job.id,w.worker.id],{cwd:process.cwd(),env:process.env,stdio:['ignore','pipe','pipe']});let output='';await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`process fixture did not claim job: ${output}`)),10000);child.stdout.on('data',chunk=>{output+=chunk.toString();if(output.includes('CLAIMED')){clearTimeout(timer);resolve()}});child.stderr.on('data',chunk=>{output+=chunk.toString()});child.on('error',reject);child.on('exit',(code,signal)=>{if(!output.includes('CLAIMED')&&(code!==null||signal))reject(new Error(`fixture exited before claim: ${output}`))})});assert.equal((await db.job.findUnique({where:{id:job.id}}))?.status,'CLAIMED');child.kill('SIGKILL');await new Promise(resolve=>setTimeout(resolve,250));const stale=await db.job.update({where:{id:job.id},data:{leaseExpiresAt:new Date(Date.now()-1000)}});assert.ok(stale.leaseExpiresAt);const recovered=await repo.recoverStale(org.id,job.id,{organizationId:org.id,actorType:'SYSTEM',eventType:'job.stale_lease_recovered',action:'process_recovery',result:'SUCCESS'});assert.equal(recovered.kind,'recovered');assert.equal((await db.job.findUnique({where:{id:job.id}}))?.status,'RETRY_QUEUED')}finally{await cleanup(org.id)}});
