import type { ExecutionRisk } from '@founder-os/core';
export interface HandlerContext{organizationId:string;workflowId:string;jobId:string;taskId:string;workerId:string;parameters:Record<string,unknown>;checkpoint:(state:Record<string,unknown>)=>Promise<void>}
export interface ExecutionHandlerResult{status:'SUCCEEDED'|'FAILED';output?:Record<string,unknown>;error?:{code:string;message:string;retryable:boolean}}
export interface ExecutionHandler{id:string;description:string;requiredCapability:string;risk:ExecutionRisk;deterministic:true;testSafe:true;validateInput:(parameters:Record<string,unknown>)=>boolean;validateOutput:(output:Record<string,unknown>)=>boolean;execute:(context:HandlerContext)=>Promise<ExecutionHandlerResult>}
const noParams=(p:Record<string,unknown>)=>Object.keys(p).length===0;const objectOutput=(p:Record<string,unknown>)=>typeof p==='object'&&p!==null&&!Array.isArray(p);
const handlers:ExecutionHandler[]=[
{id:'internal.noop',description:'Deterministic no-op for control-plane verification.',requiredCapability:'internal.execute',risk:'LOW',deterministic:true,testSafe:true,validateInput:noParams,validateOutput:objectOutput,execute:async()=>({status:'SUCCEEDED',output:{executed:true}})},
{id:'internal.calculate',description:'Deterministic arithmetic over two finite numbers.',requiredCapability:'internal.calculate',risk:'LOW',deterministic:true,testSafe:true,validateInput:p=>typeof p.a==='number'&&Number.isFinite(p.a)&&typeof p.b==='number'&&Number.isFinite(p.b)&&['add','subtract','multiply'].includes(String(p.operation)),validateOutput:p=>typeof p.result==='number'&&Number.isFinite(p.result),execute:async({parameters})=>{const a=Number(parameters.a),b=Number(parameters.b),operation=String(parameters.operation);const result=operation==='add'?a+b:operation==='subtract'?a-b:a*b;return{status:'SUCCEEDED',output:{result}}}},
{id:'internal.fail',description:'Deterministically fails for retry/failure-path verification.',requiredCapability:'internal.execute',risk:'LOW',deterministic:true,testSafe:true,validateInput:p=>typeof p.code==='string'&&typeof p.message==='string'&&typeof p.retryable==='boolean',validateOutput:noParams,execute:async({parameters})=>({status:'FAILED',error:{code:String(parameters.code),message:String(parameters.message),retryable:Boolean(parameters.retryable)}})},
{id:'internal.checkpoint',description:'Writes a controlled checkpoint for resume verification.',requiredCapability:'internal.checkpoint',risk:'LOW',deterministic:true,testSafe:true,validateInput:objectOutput,validateOutput:p=>p.checkpointed===true,execute:async({parameters,checkpoint})=>{await checkpoint({phase:'checkpointed',payload:parameters});return{status:'SUCCEEDED',output:{checkpointed:true}}}},
];
export class ExecutionHandlerRegistry{private readonly handlers=new Map(handlers.map(h=>[h.id,h]));get(id:string):ExecutionHandler|undefined{return this.handlers.get(id)}list():readonly ExecutionHandler[]{return[...this.handlers.values()].sort((a,b)=>a.id.localeCompare(b.id))}}
export function validateHandlerResult(handler:ExecutionHandler,result:ExecutionHandlerResult):{valid:true}|{valid:false;reason:string}{if(!result||(result.status!=='SUCCEEDED'&&result.status!=='FAILED'))return{valid:false,reason:'Invalid result status.'};if(result.status==='SUCCEEDED'){if(!result.output||!handler.validateOutput(result.output))return{valid:false,reason:'Handler output failed validation.'};if(result.error)return{valid:false,reason:'Successful result cannot contain an error.'}}else if(!result.error||typeof result.error.code!=='string'||typeof result.error.message!=='string'||typeof result.error.retryable!=='boolean')return{valid:false,reason:'Failed result must contain a structured error.'};return{valid:true}}
