import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';
import type { PrismaClient } from '@founder-os/db';
import type { ExecutionHandler, HandlerContext } from './execution-handlers.js';
type Provider='google'|'slack'|'github';
const TOKEN_URL:Record<Provider,string>={google:'https://oauth2.googleapis.com/token',slack:'https://slack.com/api/oauth.v2.access',github:'https://github.com/login/oauth/access_token'};
const CLIENT_KEYS:Record<Provider,[string,string]>={google:['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET'],slack:['SLACK_CLIENT_ID','SLACK_CLIENT_SECRET'],github:['GITHUB_CLIENT_ID','GITHUB_CLIENT_SECRET']};
function secretKey():Buffer{const raw=process.env.INTEGRATION_ENCRYPTION_KEY;if(!raw)throw new Error('Integration encryption is not configured.');const key=Buffer.from(raw,'hex');if(key.length!==32)throw new Error('Integration encryption key must be 32-byte hex.');return key}
function decrypt(value:string):string{const[iv,tag,body]=value.split('.');if(!iv||!tag||!body)throw new Error('Invalid encrypted integration secret.');const d=createDecipheriv('aes-256-gcm',secretKey(),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([d.update(Buffer.from(body,'base64url')),d.final()]).toString('utf8')}
function encrypt(value:string):string{const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',secretKey(),iv);const body=Buffer.concat([c.update(value,'utf8'),c.final()]);return`${iv.toString('base64url')}.${c.getAuthTag().toString('base64url')}.${body.toString('base64url')}`}
async function resolveToken(db:PrismaClient,organizationId:string,provider:Provider,accountId?:string):Promise<string>{const rows=accountId?await db.$queryRaw<Array<{id:string;accessTokenEnc:string;refreshTokenEnc:string|null;expiresAt:Date|null}>>`SELECT "id","accessTokenEnc","refreshTokenEnc","expiresAt" FROM "ConnectedIntegration" WHERE "organizationId"=${organizationId} AND "provider"=${provider} AND "accountId"=${accountId} AND "revokedAt" IS NULL ORDER BY "updatedAt" DESC LIMIT 1`:await db.$queryRaw<Array<{id:string;accessTokenEnc:string;refreshTokenEnc:string|null;expiresAt:Date|null}>>`SELECT "id","accessTokenEnc","refreshTokenEnc","expiresAt" FROM "ConnectedIntegration" WHERE "organizationId"=${organizationId} AND "provider"=${provider} AND "revokedAt" IS NULL ORDER BY "updatedAt" DESC LIMIT 1`;const row=rows[0];if(!row)throw new Error(`No connected ${provider} integration.`);if(row.expiresAt&&row.expiresAt.getTime()<=Date.now()+60000){if(!row.refreshTokenEnc)throw new Error(`${provider} integration requires reauthorization.`);const[idKey,secretKeyName]=CLIENT_KEYS[provider],clientId=process.env[idKey],clientSecret=process.env[secretKeyName];if(!clientId||!clientSecret)throw new Error(`${provider} OAuth client is not configured.`);const body=new URLSearchParams({client_id:clientId,client_secret:clientSecret,refresh_token:decrypt(row.refreshTokenEnc),grant_type:'refresh_token'});const response=await fetch(TOKEN_URL[provider],{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',accept:'application/json'},body});const token=await response.json() as Record<string,unknown>;if(!response.ok||typeof token.access_token!=='string')throw new Error(`${provider} token refresh failed.`);const accessToken=token.access_token,expiresAt=typeof token.expires_in==='number'?new Date(Date.now()+token.expires_in*1000):null,rotatedRefreshToken=typeof token.refresh_token==='string'&&token.refresh_token.length>0?token.refresh_token:null;const refreshTokenEnc=rotatedRefreshToken?encrypt(rotatedRefreshToken):row.refreshTokenEnc;const updated=await db.$executeRaw`UPDATE "ConnectedIntegration" SET "accessTokenEnc"=${encrypt(accessToken)},"refreshTokenEnc"=${refreshTokenEnc},"expiresAt"=${expiresAt},"updatedAt"=NOW() WHERE "id"=${row.id} AND "organizationId"=${organizationId} AND "expiresAt"=${row.expiresAt}`;if(updated===0){const latest=await db.$queryRaw<Array<{accessTokenEnc:string;expiresAt:Date|null}>>`SELECT "accessTokenEnc","expiresAt" FROM "ConnectedIntegration" WHERE "id"=${row.id} AND "organizationId"=${organizationId} AND "revokedAt" IS NULL LIMIT 1`;if(!latest[0])throw new Error(`${provider} integration was revoked during token refresh.`);if(latest[0].expiresAt&&latest[0].expiresAt.getTime()>Date.now())return decrypt(latest[0].accessTokenEnc)}return accessToken}return decrypt(row.accessTokenEnc)}
class ProviderRequestError extends Error{constructor(message:string,readonly retryable:boolean){super(message);this.name='ProviderRequestError'}}
async function request(url:string,token:string,init:RequestInit={}){let last:ProviderRequestError=new ProviderRequestError('Provider request failed.',true);for(let attempt=0;attempt<3;attempt++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);try{const response=await fetch(url,{...init,signal:controller.signal,headers:{authorization:`Bearer ${token}`,accept:'application/json',...(init.headers??{})}});const text=await response.text();let body:any={};try{body=text?JSON.parse(text):{}}catch{body={raw:text.slice(0,2000)}}if(response.ok&&body?.ok!==false)return body;const retryable=response.status===429||response.status>=500;const message=response.status===401?'Integration authorization expired.':response.status===403?'Integration permission denied.':`Provider request failed (${response.status}).`;last=new ProviderRequestError(message,retryable);if(!retryable)break}catch(error){last=new ProviderRequestError(error instanceof Error?error.message:'Provider request failed.',true)}finally{clearTimeout(timer)}if(attempt<2)await new Promise(r=>setTimeout(r,250*2**attempt))}throw last}
const obj=(x:unknown):x is Record<string,unknown>=>!!x&&typeof x==='object'&&!Array.isArray(x);const account=(p:Record<string,unknown>)=>typeof p.accountId==='string'&&p.accountId.length>0?p.accountId:undefined;const params=(p:Record<string,unknown>)=>{const x={...p};delete x.accountId;return x};const str=(p:Record<string,unknown>,k:string)=>typeof p[k]==='string'&&String(p[k]).length>0;const bounded=(p:Record<string,unknown>,key:string,max=100)=>{const n=Number(p[key]??20);return Number.isFinite(n)?Math.max(1,Math.min(Math.floor(n),max)):20};
function allowlisted(value:string,envName:string):boolean{const raw=process.env[envName];if(!raw)throw new Error(`${envName} is not configured; this capability is disabled.`);return new Set(raw.split(',').map(x=>x.trim()).filter(Boolean)).has(value)}
function handler(db:PrismaClient,provider:Provider,id:string,capability:string,risk:'LOW'|'HIGH'|'CRITICAL',validateInput:(p:Record<string,unknown>)=>boolean,execute:(token:string,p:Record<string,unknown>,c:HandlerContext)=>Promise<Record<string,unknown>>):ExecutionHandler{return{id,description:`${provider} governed worker capability ${capability}.`,requiredCapability:capability,risk,deterministic:false,testSafe:false,validateInput,validateOutput:obj,execute:async c=>{try{const token=await resolveToken(db,c.organizationId,provider,account(c.parameters));return{status:'SUCCEEDED',output:await execute(token,params(c.parameters),c)}}catch(error){const message=error instanceof Error?error.message:'Integration execution failed.';return{status:'FAILED',error:{code:'INTEGRATION_EXECUTION_FAILED',message,retryable:error instanceof ProviderRequestError?error.retryable:false}}}}}}
export function createIntegrationHandlers(db:PrismaClient):ExecutionHandler[]{return[
handler(db,'google','google.gmail.list','gmail.read','LOW',p=>!p.query||typeof p.query==='string',async(t,p)=>request(`https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=${bounded(p,'maxResults')}${p.query?`&q=${encodeURIComponent(String(p.query))}`:''}`,t)),
handler(db,'google','google.gmail.send','gmail.send','HIGH',p=>str(p,'to')&&str(p,'subject')&&str(p,'body'),async(t,p)=>{const raw=[`To: ${p.to}`,`Subject: ${p.subject}`,'Content-Type: text/plain; charset="UTF-8"','','',String(p.body)].join('\r\n');return request('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',t,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({raw:Buffer.from(raw).toString('base64url')})})}),
handler(db,'google','google.calendar.list','calendar.read','LOW',p=>!p.timeMin||typeof p.timeMin==='string',async(t,p)=>request(`https://www.googleapis.com/calendar/v3/calendars/primary/events?maxResults=${bounded(p,'maxResults')}${p.timeMin?`&timeMin=${encodeURIComponent(String(p.timeMin))}`:''}`,t)),
handler(db,'google','google.calendar.create','calendar.write','HIGH',p=>str(p,'summary')&&str(p,'start')&&str(p,'end'),async(t,p)=>request('https://www.googleapis.com/calendar/v3/calendars/primary/events',t,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({summary:p.summary,start:{dateTime:p.start},end:{dateTime:p.end},description:p.description})})),
handler(db,'google','google.drive.list','drive.read','LOW',p=>!p.q||typeof p.q==='string',async(t,p)=>request(`https://www.googleapis.com/drive/v3/files?pageSize=${bounded(p,'pageSize')}&fields=files(id,name,mimeType,webViewLink)${p.q?`&q=${encodeURIComponent(String(p.q))}`:''}`,t)),
handler(db,'google','google.drive.create','drive.write','HIGH',p=>str(p,'name'),async(t,p)=>request('https://www.googleapis.com/drive/v3/files',t,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:p.name,mimeType:p.mimeType??'text/plain',description:p.description})})),
handler(db,'slack','slack.channels.list','slack.read','LOW',()=>true,async t=>request('https://slack.com/api/conversations.list?limit=100',t)),
handler(db,'slack','slack.message.send','slack.send','HIGH',p=>str(p,'channel')&&str(p,'text'),async(t,p)=>request('https://slack.com/api/chat.postMessage',t,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({channel:p.channel,text:p.text})})),
handler(db,'github','github.repos.list','github.read','LOW',()=>true,async t=>request('https://api.github.com/user/repos?per_page=100',t,{headers:{accept:'application/vnd.github+json'}})),
handler(db,'github','github.issue.create','github.write','HIGH',p=>str(p,'owner')&&str(p,'repo')&&str(p,'title'),async(t,p)=>{const target=`${p.owner}/${p.repo}`;if(!allowlisted(target,'GITHUB_ALLOWED_REPOS'))throw new Error('GitHub repository is not allowlisted.');return request(`https://api.github.com/repos/${encodeURIComponent(String(p.owner))}/${encodeURIComponent(String(p.repo))}/issues`,t,{method:'POST',headers:{'content-type':'application/json','accept':'application/vnd.github+json'},body:JSON.stringify({title:p.title,body:p.body})})}),
handler(db,'github','github.workflow.dispatch','github.workflow','CRITICAL',p=>str(p,'owner')&&str(p,'repo')&&str(p,'workflow')&&str(p,'ref'),async(t,p)=>{const target=`${p.owner}/${p.repo}:${p.workflow}:${p.ref}`;if(!allowlisted(target,'GITHUB_ALLOWED_WORKFLOWS'))throw new Error('GitHub workflow/ref is not allowlisted.');if(obj(p.inputs)&&Object.keys(p.inputs).length>50)throw new Error('Too many workflow inputs.');await request(`https://api.github.com/repos/${encodeURIComponent(String(p.owner))}/${encodeURIComponent(String(p.repo))}/actions/workflows/${encodeURIComponent(String(p.workflow))}/dispatches`,t,{method:'POST',headers:{'content-type':'application/json','accept':'application/vnd.github+json'},body:JSON.stringify({ref:p.ref,inputs:obj(p.inputs)?p.inputs:{}})});return{dispatched:true}}),
]}
