import type { PrismaClient } from '@founder-os/db';
import { AUDIT_EVENTS, JobRepository, WorkerRepository, recordAuditEvent, type AuditEventType } from '@founder-os/db';
import type { JobStatus } from '@founder-os/core';
import type { ExecutionHandlerResult } from './execution-handlers.js';

export class JobService {
  private readonly repository: JobRepository;
  private readonly workers: WorkerRepository;
  constructor(private readonly db: PrismaClient) { this.repository = new JobRepository(db); this.workers = new WorkerRepository(db); }
  list(organizationId:string){return this.repository.list(organizationId)}
  listRunnable(organizationId:string,now=new Date(),limit=50){return this.repository.listRunnable(organizationId,now,limit)}
  get(organizationId:string,id:string){return this.repository.get(organizationId,id)}
  create(input:Parameters<JobRepository['create']>[0],actorId?:string){return this.repository.create(input,{organizationId:input.organizationId,actorId,actorType:actorId?'USER':'SYSTEM',eventType:AUDIT_EVENTS.JOB_CREATED,action:'create',result:'SUCCESS'});}
  async authenticateWorker(organizationId:string,workerId:string,credential:string){const worker=await this.workers.authenticate(organizationId,workerId,credential,{organizationId,actorType:'SYSTEM',eventType:AUDIT_EVENTS.WORKER_AUTHENTICATED,action:'authenticate',result:'SUCCESS'});if(!worker)throw new Error('Worker authentication failed.');return worker;}
  async claimAuthenticated(organizationId:string,id:string,workerId:string,credential:string,leaseMs=30000){await this.authenticateWorker(organizationId,workerId,credential);return this.repository.claim(organizationId,id,workerId,leaseMs,{organizationId,actorType:'AGENT',eventType:AUDIT_EVENTS.JOB_CLAIMED,action:'claim',result:'SUCCESS',metadata:{workerId}});}
  claim(organizationId:string,id:string,workerId:string,leaseMs=30000){return this.repository.claim(organizationId,id,workerId,leaseMs,{organizationId,actorType:'SYSTEM',eventType:AUDIT_EVENTS.JOB_CLAIMED,action:'claim',result:'SUCCESS',metadata:{workerId}});}
  start(organizationId:string,id:string,workerId:string){return this.repository.transition(organizationId,id,'CLAIMED','RUNNING',workerId,{organizationId,actorType:'SYSTEM',eventType:AUDIT_EVENTS.JOB_STARTED,action:'start',result:'SUCCESS',metadata:{workerId}});}
  waitForApproval(organizationId:string,id:string,workerId:string,approvalId:string){return this.repository.setApprovalBlocked(organizationId,id,workerId,approvalId,{organizationId,actorType:'AGENT',eventType:AUDIT_EVENTS.WORKFLOW_APPROVAL_BLOCKED,action:'approval_required',result:'SUCCESS',metadata:{workerId,approvalId}});}
  resolveApproval(organizationId:string,id:string,approved:boolean){return this.repository.resolveApproval(organizationId,id,approved,{organizationId,actorType:'SYSTEM',eventType:approved?AUDIT_EVENTS.EXECUTION_APPROVED:AUDIT_EVENTS.EXECUTION_REJECTED,action:approved?'approval_granted':'approval_rejected',result:approved?'SUCCESS':'DENIED'});}
  heartbeat(organizationId:string,id:string,workerId:string,leaseMs=30000){return this.repository.heartbeat(organizationId,id,workerId,leaseMs)}
  succeed(organizationId:string,id:string,workerId:string){return this.repository.transition(organizationId,id,'RUNNING','SUCCEEDED',workerId,{organizationId,actorType:'SYSTEM',eventType:AUDIT_EVENTS.JOB_SUCCEEDED,action:'succeed',result:'SUCCESS',metadata:{workerId}});}
  succeedWithResult(organizationId:string,id:string,workerId:string,result:ExecutionHandlerResult,handlerId:string){return this.repository.transition(organizationId,id,'RUNNING','SUCCEEDED',workerId,{organizationId,actorType:'SYSTEM',eventType:AUDIT_EVENTS.JOB_SUCCEEDED,action:'succeed',result:'SUCCESS',metadata:{workerId,handlerId}},new Date(),undefined,{status:'SUCCEEDED',output:result.output,handlerId,validatedAt:new Date()});}
  fail(organizationId:string,id:string,workerId:string,code:string,message:string,retryable:boolean){return this.repository.fail(organizationId,id,workerId,{code,message,retryable},{organizationId,actorType:'SYSTEM',eventType:AUDIT_EVENTS.JOB_FAILED,action:'fail',result:'FAILURE',metadata:{workerId,code,retryable}});}
  failWithResult(organizationId:string,id:string,workerId:string,result:ExecutionHandlerResult,handlerId:string){const error=result.error!;return this.repository.fail(organizationId,id,workerId,{code:error.code,message:error.message,retryable:error.retryable},{organizationId,actorType:'SYSTEM',eventType:AUDIT_EVENTS.JOB_FAILED,action:'fail',result:'FAILURE',metadata:{workerId,code:error.code,retryable:error.retryable,handlerId}},new Date(),{status:'FAILED',error,handlerId,validatedAt:new Date()});}
  cancel(organizationId:string,id:string,workerId:string){return this.repository.transition(organizationId,id,'RUNNING','CANCELLED',workerId,{organizationId,actorType:'SYSTEM',eventType:AUDIT_EVENTS.JOB_CANCELLED,action:'cancel',result:'SUCCESS',metadata:{workerId}});}
  recoverStale(organizationId:string,id:string){return this.repository.recoverStale(organizationId,id,{organizationId,actorType:'SYSTEM',eventType:AUDIT_EVENTS.JOB_STALE_LEASE_RECOVERED,action:'recover_stale',result:'SUCCESS'});}
  checkpoint(organizationId:string,id:string,workerId:string,state:Record<string,unknown>){return this.repository.checkpoint(organizationId,id,state,workerId,{organizationId,actorType:'SYSTEM',eventType:AUDIT_EVENTS.JOB_CHECKPOINT_CREATED,action:'checkpoint',result:'SUCCESS',metadata:{workerId}});}
  audit(organizationId:string,eventType:AuditEventType,resourceType:string,resourceId:string,action:string,result:'SUCCESS'|'FAILURE'|'DENIED',metadata:Record<string,unknown>={}){return recordAuditEvent(this.db,{organizationId,actorType:'SYSTEM',eventType,resourceType,resourceId,action,result,metadata:metadata as never});}
  async resumeCandidate(organizationId:string,id:string){const job=await this.repository.get(organizationId,id);if(!job)return null;if(job.status==='RETRY_QUEUED')return job;if(job.status==='CLAIMED'||job.status==='RUNNING')return job.leaseExpiresAt&&job.leaseExpiresAt<=new Date()?this.repository.recoverStale(organizationId,id,{organizationId,actorType:'SYSTEM',eventType:AUDIT_EVENTS.JOB_STALE_LEASE_RECOVERED,action:'recover_stale',result:'SUCCESS'}):job;return null;}
}
export type {JobStatus};