import type { PrismaClient } from '@founder-os/db';
import { AUDIT_EVENTS, ensureWorkflowJob, reconcileWorkflow } from '@founder-os/db';
import { JobDispatcher } from './job-dispatcher.js';
import { WorkerRuntime, type ExecutionAuthorizer } from './worker-runtime.js';
export type CredentialResolver=(organizationId:string,workerId:string)=>Promise<string|null>;
export interface OrchestrationResult{workflowId:string;before:string;after:string;tasksReady:number;jobsCreated:number;jobsDispatched:number;jobsCompleted:number;jobsFailed:number;jobsRetrying:number;jobsWaitingApproval:number;workersSelected:string[];workersUnavailable:number;stoppedReason:string}
export interface OrchestratorOptions{resolveCredential:CredentialResolver;authorizeExecution:ExecutionAuthorizer;leaseMs?:number}
export class Orchestrator{private readonly dispatcher:JobDispatcher;private readonly runtime:WorkerRuntime;constructor(private readonly db:PrismaClient,private readonly options:OrchestratorOptions){this.dispatcher=new JobDispatcher(db,options.leaseMs);this.runtime=new WorkerRuntime(db,{leaseMs:options.leaseMs,authorizeExecution:options.authorizeExecution})}
async orchestrate(organizationId:string,workflowId:string):Promise<OrchestrationResult>{const before=await this.db.workflow.findFirst({where:{organizationId,id:workflowId}});if(!before)return{workflowId,before:'MISSING',after:'MISSING',tasksReady:0,jobsCreated:0,jobsDispatched:0,jobsCompleted:0,jobsFailed:0,jobsRetrying:0,jobsWaitingApproval:0,workersSelected:[],workersUnavailable:0,stoppedReason:'WORKFLOW_NOT_FOUND'};await this.db.auditEvent.create({data:{organization:{connect:{id:organizationId}},actorType:'SYSTEM',eventType:AUDIT_EVENTS.WORKFLOW_UPDATED,resourceType:'Workflow',resourceId:workflowId,action:'orchestrator_cycle_started',result:'SUCCESS',metadata:{workflowId}}});const rec=await reconcileWorkflow(this.db,organizationId,workflowId,{organizationId,actorType:'SYSTEM',action:'orchestrator_reconcile',result:'SUCCESS'});let created=0;let dispatched=0;let completed=0;let failed=0;let retrying=0;let waiting=0;let unavailable=0;const selected:string[]=[];let wf=await this.db.workflow.findFirst({where:{organizationId,id:workflowId}});if(!wf)return{workflowId,before:before.status,after:'MISSING',tasksReady:0,jobsCreated:0,jobsDispatched:0,jobsCompleted:0,jobsFailed:0,jobsRetrying:0,jobsWaitingApproval:0,workersSelected:selected,workersUnavailable:0,stoppedReason:'WORKFLOW_REMOVED'};if(wf.status==='COMPLETED'||wf.status==='CANCELLED')return this.finish(organizationId,workflowId,before.status,wf.status,0,created,dispatched,completed,failed,retrying,waiting,selected,unavailable,'TERMINAL');if(!wf.currentJobId){const ensured=await ensureWorkflowJob(this.db,organizationId,workflowId,{organizationId,actorType:'SYSTEM',action:'orchestrator_create_job',result:'SUCCESS'});if(ensured.kind==='created')created++;if(ensured.kind==='blocked')return this.finish(organizationId,workflowId,before.status,'BLOCKED',0,created,dispatched,completed,failed,retrying,waiting,selected,unavailable,ensured.reason);wf=await this.db.workflow.findFirst({where:{organizationId,id:workflowId}});if(!wf||!wf.currentJobId)return this.finish(organizationId,workflowId,before.status,wf?.status??'MISSING',0,created,dispatched,completed,failed,retrying,waiting,selected,unavailable,'NO_CURRENT_JOB')}
const current=await this.db.job.findFirst({where:{organizationId,id:wf.currentJobId}});if(!current)return this.finish(organizationId,workflowId,before.status,wf.status,0,created,dispatched,completed,failed,retrying,waiting,selected,unavailable,'CURRENT_JOB_MISSING');if(current.status==='WAITING_APPROVAL'){waiting=1;return this.finish(organizationId,workflowId,before.status,wf.status,0,created,dispatched,completed,failed,retrying,waiting,selected,unavailable,'WAITING_APPROVAL');}if(current.status==='SUCCEEDED'){completed=1;return this.finish(organizationId,workflowId,before.status,wf.status,0,created,dispatched,completed,failed,retrying,waiting,selected,unavailable,'SUCCEEDED_RECONCILED');}if(current.status==='FAILED'){failed=1;return this.finish(organizationId,workflowId,before.status,wf.status,0,created,dispatched,completed,failed,retrying,waiting,selected,unavailable,'FAILED');}if(current.status==='RETRY_QUEUED')retrying=1;if(current.status==='QUEUED'||current.status==='RETRY_QUEUED'){const d=await this.dispatcher.dispatchNext(organizationId);if(d.kind==='dispatched'){dispatched=1;selected.push(d.workerId!);const credential=await this.options.resolveCredential(organizationId,d.workerId!);if(credential){const run=await this.runtime.run(organizationId,d.jobId,d.workerId!,credential);if(run.kind==='succeeded')completed=1;if(run.kind==='failed')failed=1;if(run.kind==='waiting_approval')waiting=1;if(run.kind==='denied')failed=1;}else unavailable=1;}else if(d.kind==='no_worker')unavailable=1;}
const after=await this.db.workflow.findFirst({where:{organizationId,id:workflowId}});return this.finish(organizationId,workflowId,before.status,after?.status??wf.status,1,created,dispatched,completed,failed,retrying,waiting,selected,unavailable,rec.kind==='consistent'?'NO_CHANGE':rec.kind)}
private async finish(org:string,wf:string,before:string,after:string,ready:number,created:number,dispatched:number,completed:number,failed:number,retrying:number,waiting:number,workers:string[],unavailable:number,reason:string):Promise<OrchestrationResult>{await this.db.auditEvent.create({data:{organization:{connect:{id:org}},actorType:'SYSTEM',eventType:AUDIT_EVENTS.WORKFLOW_UPDATED,resourceType:'Workflow',resourceId:wf,action:'orchestrator_cycle_completed',result:'SUCCESS',metadata:{workflowId:wf,before,after,reason,created,dispatched,completed,failed,retrying,waiting,workersUnavailable:unavailable}}});return{workflowId:wf,before,after,tasksReady:ready,jobsCreated:created,jobsDispatched:dispatched,jobsCompleted:completed,jobsFailed:failed,jobsRetrying:retrying,jobsWaitingApproval:waiting,workersSelected:workers,workersUnavailable:unavailable,stoppedReason:reason}}
}
