-- V1.04 migration ordering compatibility shim.
--
-- This migration was originally authored as an additive migration that assumed
-- the initial control-plane tables already existed, but its timestamp placed it
-- before that initial migration in a clean database. Keep the historical
-- migration identifier intact and apply the V1.04 schema changes in the
-- correctly ordered migration 20260910155000_v104_control_plane_foundations_apply.
--
-- No schema changes are performed here.
