import test from 'node:test';
import assert from 'node:assert/strict';
import * as core from '../src/index.js';
import { WorkforceRegistry, buildWorkforceSelectionProposal, buildDelegationProposal, buildDelegationJobInput, DeterministicTestWorker, validateWorkerResult, validateQA, type CapabilityDefinition, type WorkforceRole, type ProviderDefinition, type WorkforceModelDefinition, type WorkforceTaskRequirement, type ControlPlaneWorkerBinding } from '../src/index.js';

const scope={organization:true as const,projectId:'project-a'};
const role=():WorkforceRole=>({roleId:'engineer',organizationId:'org-a',name:'Engineer',category:'engineering',description:'bounded engineer',responsibilities:['implement'],status:'ACTIVE',employmentType:'PERMANENT',capabilityRequirements:['SOFTWARE_ENGINEERING'],contextScope:scope,qaResponsibility:{required:true,independent:true,qualityCriteria:['output is valid']},escalationPolicy:{reasons:['QUALITY_FAILURE','PROVIDER_UNAVAILABLE'],target:'LEO'},createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'});
const capability=():CapabilityDefinition=>({capabilityId:'SOFTWARE_ENGINEERING',description:'software engineering',contract:{capabilityId:'SOFTWARE_ENGINEERING',requiredInputs:['task'],expectedOutputs:['result'],qualityCriteria:['output is valid'],risk:'LOW',requiredContextScopes:['PROJECT'],qa:{required:true,independent:true,qualityCriteria:['output is valid']},escalation:{reasons:['QUALITY_FAILURE'],target:'LEO'},modelRequirements:['coding'],compatibleProviderCharacteristics:['deterministic']}});
const provider=():ProviderDefinition=>({providerId:'provider-test',providerName:'Deterministic Provider',providerType:'TEST',availability:'AVAILABLE',costClass:'FREE',supportedCapabilities:['SOFTWARE_ENGINEERING'],routingEligible:true,provenance:'test'});
const model=():WorkforceModelDefinition=>({modelId:'model-test',providerId:'provider-test',modelName:'Deterministic Model',capabilities:['SOFTWARE_ENGINEERING'],contextLimit:10000,qualityTier:'STANDARD',expectedLatencyMs:10,costClass:'FREE',availability:'AVAILABLE',routingEligible:true,provenance:'test'});
const task=(o:Partial<WorkforceTaskRequirement>={}):WorkforceTaskRequirement=>({taskId:'task-1',organizationId:'org-a',requiredCapabilities:['SOFTWARE_ENGINEERING'],risk:'LOW',requiredContext:scope,freeFirst:true,...o});
function proposalFor(t=task()) { const r=new WorkforceRegistry(); r.registerCapability(capability()); r.registerRole(role()); r.registerProvider(provider()); r.registerModel(model()); const policy={organizationId:'org-a',freeFirst:true,requireFreeOption:true,requireProjectContext:true,maxLatencyMs:1000}; const selection=buildWorkforceSelectionProposal('org-a','corr-1',[t],[role()],r,policy); return buildDelegationProposal('org-a','owner-1','corr-1',selection,t,role(),capability().contract); }
function bindingFor(t=task(), overrides:Partial<ControlPlaneWorkerBinding>={}) { const proposal=proposalFor(t); return { proposal, binding: { workerId:'worker-a',organizationId:'org-a',taskId:t.taskId,delegationId:proposal.proposalId,roleId:'engineer',capabilities:['SOFTWARE_ENGINEERING'],context:scope,providerId:'provider-test',modelId:'model-test',risk:t.risk,...overrides } satisfies ControlPlaneWorkerBinding }; }

test('delegation proposal is proposal-only and has no execution authority',()=>{const {proposal}=bindingFor();assert.equal(proposal.authority,'PROPOSAL_ONLY');for(const f of ['workerId','execute','dispatch','credentialId','authorization','approvalGranted'])assert.equal(f in proposal,false);});
test('delegation core exposes no authorization grant API',()=>{assert.equal('authorizeDelegation' in core,false);assert.equal('createAuthorizedWorker' in core,false);});
test('control-plane worker binding must identify an existing worker',()=>{const {proposal,binding}=bindingFor();assert.throws(()=>buildDelegationJobInput(proposal,{...binding,workerId:''}),/worker identity/);});
test('high-risk delegation remains an approval requirement, not an approval grant',()=>{const t=task({risk:'HIGH'});const {proposal,binding}=bindingFor(t);assert.equal(proposal.approvalRequired,true);assert.throws(()=>buildDelegationJobInput(proposal,{...binding,risk:'LOW'}),/risk cannot be downgraded/);});
test('critical risk remains represented as critical and cannot be downgraded',()=>{const t=task({risk:'CRITICAL'});const {proposal,binding}=bindingFor(t);assert.equal(proposal.risk,'CRITICAL');assert.throws(()=>buildDelegationJobInput(proposal,{...binding,risk:'HIGH'}),/risk cannot be downgraded/);});
test('delegation job input consumes control-plane worker binding without authorizing it',()=>{const {proposal,binding}=bindingFor();const job=buildDelegationJobInput(proposal,binding);assert.equal(job.organizationId,'org-a');assert.equal(job.taskId,'task-1');assert.equal(job.workerIdentityId,'worker-a');assert.equal(job.idempotencyKey,'delegation:org-a:task-1:corr-1');for(const f of ['execute','dispatch','credential','approvalGranted'])assert.equal(f in job,false);});
test('workflow binding is preserved as a non-authorizing durable Job field',()=>{const {proposal,binding}=bindingFor(task(),{workflowId:'workflow-a'});const job=buildDelegationJobInput(proposal,binding);assert.equal(job.workflowId,'workflow-a');});
test('durable job input preserves risk/context without granting authority',()=>{const {proposal,binding}=bindingFor();const job=buildDelegationJobInput(proposal,binding);assert.equal(job.metadata.risk,'LOW');assert.deepEqual(job.metadata.authorizedContext,scope);for(const f of ['grantedPermissions','grantedCapabilities','credentialId','permissionGrant','capabilityGrant','authorization'])assert.equal(f in job.metadata,false);});
test('cross-organization delegation fails closed',()=>{const {proposal,binding}=bindingFor();assert.throws(()=>buildDelegationJobInput({...proposal,organizationId:'org-b'},binding),/binding does not match/);});
test('capability enforcement rejects unsuitable control-plane binding',()=>{const {proposal,binding}=bindingFor();assert.throws(()=>buildDelegationJobInput(proposal,{...binding,capabilities:[]}),/Missing workforce capabilities/);});
test('provider/model binding must match the selected eligible target',()=>{const {proposal,binding}=bindingFor();assert.throws(()=>buildDelegationJobInput(proposal,{...binding,providerId:'other'}),/provider\/model mismatch/);});
test('worker result validation is proposal-bound data validation only',()=>{const {binding}=bindingFor();const result=new DeterministicTestWorker('SUCCESS',{ok:true}).execute({worker:binding,context:binding.context});assert.doesNotThrow(()=>validateWorkerResult(binding,result));});
test('malformed result fails closed',()=>{const {binding}=bindingFor();const result=new DeterministicTestWorker('MALFORMED_RESULT').execute({worker:binding,context:binding.context});assert.throws(()=>validateWorkerResult(binding,result),/binding mismatch|provenance mismatch/);});
test('QA supports PASS, REWORK and ESCALATE only after result validation',()=>{const {binding,proposal}=bindingFor();const result=new DeterministicTestWorker('SUCCESS',{ok:true}).execute({worker:binding,context:binding.context});assert.doesNotThrow(()=>validateWorkerResult(binding,result));assert.equal(validateQA(result,proposal.capabilityContract.qualityCriteria,'PASS','pass').decision,'PASS');assert.equal(validateQA(result,proposal.capabilityContract.qualityCriteria,'REWORK','rework').decision,'REWORK');assert.equal(validateQA(result,proposal.capabilityContract.qualityCriteria,'ESCALATE','escalate').decision,'ESCALATE');});
test('worker binding cannot expand context',()=>{const {proposal,binding}=bindingFor();assert.throws(()=>buildDelegationJobInput(proposal,{...binding,context:{organization:true,projectId:'project-b'}}),/context exceeds/);});
test('worker binding contains no credential, permission, spending, dispatch or external-action authority',()=>{const {binding}=bindingFor();for(const f of ['credentialId','grantedPermissions','permissionGrant','spending','externalAction','dispatch','execute'])assert.equal(f in binding,false);});
test('core delegation contains no independent execution or idempotency state',()=>{const {proposal,binding}=bindingFor();const job=buildDelegationJobInput(proposal,binding);assert.deepEqual(Object.keys(job).sort(),['idempotencyKey','metadata','organizationId','taskId','workerIdentityId','workflowId']);});
