import test from 'node:test';
import assert from 'node:assert/strict';
import { WorkforceRegistry, buildWorkforceSelectionProposal, buildDelegationProposal, authorizeDelegation, createAuthorizedWorker, buildAuthorizedDelegationJobInput, DeterministicTestWorker, validateWorkerResult, validateQA, type CapabilityDefinition, type WorkforceRole, type ProviderDefinition, type WorkforceModelDefinition, type WorkforceTaskRequirement } from '../src/index.js';

const scope={organization:true as const,projectId:'project-a'};
const role=():WorkforceRole=>({roleId:'engineer',organizationId:'org-a',name:'Engineer',category:'engineering',description:'bounded engineer',responsibilities:['implement'],status:'ACTIVE',employmentType:'PERMANENT',capabilityRequirements:['SOFTWARE_ENGINEERING'],contextScope:scope,qaResponsibility:{required:true,independent:true,qualityCriteria:['output is valid']},escalationPolicy:{reasons:['QUALITY_FAILURE','PROVIDER_UNAVAILABLE'],target:'LEO'},createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'});
const capability=():CapabilityDefinition=>({capabilityId:'SOFTWARE_ENGINEERING',description:'software engineering',contract:{capabilityId:'SOFTWARE_ENGINEERING',requiredInputs:['task'],expectedOutputs:['result'],qualityCriteria:['output is valid'],risk:'LOW',requiredContextScopes:['PROJECT'],qa:{required:true,independent:true,qualityCriteria:['output is valid']},escalation:{reasons:['QUALITY_FAILURE'],target:'LEO'},modelRequirements:['coding'],compatibleProviderCharacteristics:['deterministic']}});
const provider=():ProviderDefinition=>({providerId:'provider-test',providerName:'Deterministic Provider',providerType:'TEST',availability:'AVAILABLE',costClass:'FREE',supportedCapabilities:['SOFTWARE_ENGINEERING'],routingEligible:true,provenance:'test'});
const model=():WorkforceModelDefinition=>({modelId:'model-test',providerId:'provider-test',modelName:'Deterministic Model',capabilities:['SOFTWARE_ENGINEERING'],contextLimit:10000,qualityTier:'STANDARD',expectedLatencyMs:10,costClass:'FREE',availability:'AVAILABLE',routingEligible:true,provenance:'test'});
const task=(o:Partial<WorkforceTaskRequirement>={}):WorkforceTaskRequirement=>({taskId:'task-1',organizationId:'org-a',requiredCapabilities:['SOFTWARE_ENGINEERING'],risk:'LOW',requiredContext:scope,freeFirst:true,...o});
function setup(t=task()) { const r=new WorkforceRegistry(); r.registerCapability(capability()); r.registerRole(role()); r.registerProvider(provider()); r.registerModel(model()); const policy={organizationId:'org-a',freeFirst:true,requireFreeOption:true,requireProjectContext:true,maxLatencyMs:1000}; const selection=buildWorkforceSelectionProposal('org-a','corr-1',[t],[role()],r,policy); const proposal=buildDelegationProposal('org-a','owner-1','corr-1',selection,t,role(),capability().contract); const auth=authorizeDelegation(proposal,role(),proposal.selectedProviderModel,'worker-a',false); const worker=createAuthorizedWorker(auth,t.taskId,role().roleId); return {proposal,auth,worker}; }

test('delegation proposal is proposal-only and has no execution authority',()=>{const {proposal}=setup();assert.equal(proposal.authority,'PROPOSAL_ONLY');for(const f of ['workerId','execute','dispatch','credentialId','authorization'])assert.equal(f in proposal,false);});
test('authorization requires an existing worker identity explicitly',()=>{const {proposal}=setup();assert.throws(()=>authorizeDelegation(proposal,role(),proposal.selectedProviderModel,'',false),/worker identity/);});
test('approval is required before high-risk authorization',()=>{const {proposal}=setup(task({risk:'HIGH'}));assert.throws(()=>authorizeDelegation(proposal,role(),proposal.selectedProviderModel,'worker-a',false),/Approval is required/);});
test('critical risk remains denied',()=>{const {proposal}=setup(task({risk:'CRITICAL'}));assert.throws(()=>authorizeDelegation(proposal,role(),proposal.selectedProviderModel,'worker-a',true),/DENY/);});
test('authorized worker is bound to organization, task, delegation and capability',()=>{const {worker}=setup();assert.deepEqual(worker,{...worker,workerId:'worker-a',organizationId:'org-a',taskId:'task-1',status:'AUTHORIZED'});assert.deepEqual(worker.capabilities,['SOFTWARE_ENGINEERING']);});
test('cross-organization delegation fails closed',()=>{const {proposal}=setup();assert.throws(()=>authorizeDelegation({...proposal,organizationId:'org-b'},role(),proposal.selectedProviderModel,'worker-a',false),/organization/);});
test('capability enforcement rejects unsuitable role',()=>{const {proposal}=setup();assert.throws(()=>authorizeDelegation(proposal,{...role(),capabilityRequirements:['TECHNICAL_QA']},proposal.selectedProviderModel,'worker-a',false),/Missing workforce capabilities/);});
test('authorized delegation produces durable Phase 1 Job input only',()=>{const {proposal,worker}=setup();const job=buildAuthorizedDelegationJobInput(proposal,worker);assert.equal(job.organizationId,'org-a');assert.equal(job.taskId,'task-1');assert.equal(job.workerIdentityId,'worker-a');assert.equal(job.idempotencyKey,'delegation:org-a:task-1:corr-1');for(const f of ['execute','dispatch','credential','approvalGranted'])assert.equal(f in job,false);});
test('durable job input preserves risk/context without granting authority',()=>{const {proposal,worker}=setup();const job=buildAuthorizedDelegationJobInput(proposal,worker);assert.equal(job.metadata.risk,'LOW');assert.deepEqual(job.metadata.authorizedContext,scope);for(const f of ['grantedPermissions','grantedCapabilities','credentialId','permissionGrant','capabilityGrant','authorization'])assert.equal(f in job.metadata,false);});
test('deterministic worker remains a result fixture, not an execution orchestrator',()=>{const {worker}=setup();const result=new DeterministicTestWorker('SUCCESS',{ok:true}).execute({worker,context:worker.context});assert.doesNotThrow(()=>validateWorkerResult(worker,result));});
test('malformed result fails closed',()=>{const {worker}=setup();const result=new DeterministicTestWorker('MALFORMED_RESULT').execute({worker,context:worker.context});assert.throws(()=>validateWorkerResult(worker,result),/binding mismatch|provenance mismatch/);});
test('QA supports PASS, REWORK and ESCALATE only after result validation',()=>{const {worker,proposal}=setup();const result=new DeterministicTestWorker('SUCCESS',{ok:true}).execute({worker,context:worker.context});assert.equal(validateQA(result,proposal.capabilityContract.qualityCriteria,'PASS','pass').decision,'PASS');assert.equal(validateQA(result,proposal.capabilityContract.qualityCriteria,'REWORK','rework').decision,'REWORK');assert.equal(validateQA(result,proposal.capabilityContract.qualityCriteria,'ESCALATE','escalate').decision,'ESCALATE');});
test('authorized context cannot be expanded',()=>{const {worker}=setup();assert.throws(()=>new DeterministicTestWorker('SUCCESS').execute({worker,context:{organization:true,projectId:'project-b'}}),/context exceeds/);});
test('worker has no credential, permission, spending, dispatch or external-action authority',()=>{const {worker}=setup();for(const f of ['credentialId','grantedPermissions','permissionGrant','spending','externalAction','dispatch','execute'])assert.equal(f in worker,false);});
test('core contains no independent delegation execution or idempotency state',()=>{const {proposal,worker}=setup();const job=buildAuthorizedDelegationJobInput(proposal,worker);assert.deepEqual(Object.keys(job).sort(),['idempotencyKey','metadata','organizationId','taskId','workerIdentityId']);});
