import assert from 'node:assert/strict';
import test from 'node:test';
import { DeterministicMediaProducer, MediaProductionGateway, MediaProducerRegistry, evaluateMediaQa, verifyMediaAsset } from '../src/media-production.js';
import type { ControlPlaneWorkerBinding } from '../src/delegation.js';

const worker: ControlPlaneWorkerBinding = { workerId:'worker-1', organizationId:'org-1', taskId:'task-1', delegationId:'del-1', roleId:'creator', capabilities:['VIDEO_EDITING','AUDIO_GENERATION','VISUAL_DESIGN','CONTENT_QA','TECHNICAL_QA'], context:{organization:true,projectId:'project-1'}, providerId:'provider-1', modelId:'model-1', risk:'LOW' };
const schema = { name:'object', validate:(v:unknown) => typeof v==='object' && v!==null };
function setup(){ const registry=new MediaProducerRegistry(); registry.register({producerId:'video-test',organizationId:'org-1',capabilityId:'VIDEO_EDITING',mediaType:'VIDEO',input:schema,output:{name:'asset',validate:v=>typeof v==='object'&&v!==null},qualityCriteria:['readable render','duration valid'],risk:'LOW',requiredApproval:false,provenance:'test',status:'AVAILABLE'},new DeterministicMediaProducer('video-test','VIDEO','mp4','video/mp4',input=>JSON.stringify(input))); return new MediaProductionGateway(registry); }
const request=(overrides:Record<string,unknown>={})=>({producerId:'video-test',organizationId:'org-1',taskId:'task-1',workerId:'worker-1',capabilityId:'VIDEO_EDITING',input:{scenes:[]},correlationId:'corr-1',idempotencyKey:'idem-1',...overrides});

test('V3.04 allows only an authoritative worker through typed capability policy',()=>{const result=setup().produce(request(),{worker,approvalValid:false});assert.equal(result.status,'SUCCESS');if(result.status==='SUCCESS')assert.equal(result.asset.status,'PRODUCED');});
test('V3.04 rejects cross-organization and wrong-worker requests',()=>{const gateway=setup();assert.equal(gateway.produce(request({organizationId:'org-2'}),{worker,approvalValid:false}).status,'FAILURE');assert.equal(gateway.produce(request({workerId:'attacker'}),{worker,approvalValid:false}).status,'FAILURE');});
test('V3.04 rejects malformed input',()=>{assert.deepEqual(setup().produce(request({input:'bad'}),{worker,approvalValid:false}),{status:'FAILURE',code:'MALFORMED_INPUT',message:'Production input failed its typed schema',retryable:false});});
test('V3.04 requires approval for high risk',()=>{const registry=new MediaProducerRegistry();registry.register({producerId:'high',organizationId:'org-1',capabilityId:'VIDEO_EDITING',mediaType:'VIDEO',input:schema,output:{name:'asset',validate:v=>typeof v==='object'&&v!==null},qualityCriteria:['qa'],risk:'HIGH',requiredApproval:true,provenance:'test',status:'AVAILABLE'},new DeterministicMediaProducer('high','VIDEO','mp4','video/mp4',()=> 'safe'));assert.equal(new MediaProductionGateway(registry).produce(request({producerId:'high'}),{worker,approvalValid:false}).status,'FAILURE');});
test('V3.04 verifies technical and content QA before accepting an asset',()=>{const produced=setup().produce(request(),{worker,approvalValid:false});assert.equal(produced.status,'SUCCESS');if(produced.status!=='SUCCESS')return;const report=evaluateMediaQa(produced.asset,[true,true,true],[true,true]);assert.equal(report.verified,true);const verified=verifyMediaAsset(produced.asset,report);assert.equal(verified.status,'VERIFIED');assert.equal(verified.validationStatus,'VALID');});
test('V3.04 rejects incomplete QA and publication-shaped output',()=>{const produced=setup().produce(request(),{worker,approvalValid:false});assert.equal(produced.status,'SUCCESS');if(produced.status!=='SUCCESS')return;assert.equal(evaluateMediaQa(produced.asset,[true,false],[true]).verified,false);const malicious={...produced.asset,metadata:{publish:true}};assert.throws(()=>verifyMediaAsset(malicious,evaluateMediaQa(malicious,[true],[true])));});
test('V3.04 deduplicates successful production by idempotency key',()=>{const gateway=setup();const first=gateway.produce(request(),{worker,approvalValid:false});const second=gateway.produce(request(),{worker,approvalValid:false});assert.deepEqual(second,first);});
