import test from 'node:test';
import assert from 'node:assert/strict';
import { ModelRegistry, ModelRuntime, routeModel, type ModelDefinition, type ModelProvider, type ModelRequest, type ModelResponse } from '../src/index.js';

const def = (o: Partial<ModelDefinition> = {}): ModelDefinition => ({ providerId: 'p', modelId: 'm', capabilities: ['reasoning', 'structured_output'], qualityTier: 'STANDARD', cost: { costPerInputUnit: 0.1, costPerOutputUnit: 0.2, currency: 'TEST' }, latency: { expectedLatencyMs: 1000 }, availability: 'AVAILABLE', context: { maxInputUnits: 10000 }, version: '1', provenance: 'test', ...o });
const req = (o: Record<string, unknown> = {}) => ({ requestId: 'r1', organizationId: 'org-a', ownerUserId: 'owner-1', purpose: 'test', requiredCapabilities: ['reasoning'] as const, preferredCapabilities: [] as const, minimumQualityTier: 'BASIC' as const, latencySensitive: false, maxCost: 1, allowFallback: true, timestamp: '2026-09-10T12:00:00.000Z', correlationId: 'c1', input: { objective: 'test' }, ...o });
const pol = (o: Partial<Parameters<typeof routeModel>[2]> = {}) => ({ policyVersion: 'routing-v1', allowFallback: true, requireOrganizationMatch: true, ...o });
function success(providerId: string, modelId: string): ModelProvider { return { providerId, modelId, generate(input: ModelRequest): ModelResponse { return { responseId: `${input.requestId}:${providerId}:${modelId}:response`, requestId: input.requestId, providerId, modelId, status: 'SUCCESS', output: { kind: 'test-output', input: input.input }, timestamp: input.timestamp, correlationId: input.correlationId, provenance: { providerId, modelId, requestId: input.requestId, correlationId: input.correlationId, deterministic: true } }; } }; }
function failure(providerId: string, modelId: string, code: 'PROVIDER_UNAVAILABLE' | 'TIMEOUT' | 'PROVIDER_FAILURE'): ModelProvider { return { providerId, modelId, generate(input): ModelResponse { return { responseId: `${input.requestId}:failure`, requestId: input.requestId, providerId, modelId, status: 'FAILURE', failure: { code, message: code, retryable: true }, timestamp: input.timestamp, correlationId: input.correlationId, provenance: { providerId, modelId, requestId: input.requestId, correlationId: input.correlationId, deterministic: true } }; } }; }

test('required capabilities match and missing capabilities fail closed', () => { const d = def(); const r = new ModelRegistry([d], [success('p', 'm')]); assert.equal(routeModel(req(), r, pol()).selectedModelId, 'm'); assert.throws(() => routeModel(req({ requiredCapabilities: ['vision'] }), r, pol()), /NO_ELIGIBLE_MODEL/); });
test('preferred capabilities, quality, latency and budget participate deterministically', () => { const ms = [def({ providerId: 'a', modelId: 'slow-premium', qualityTier: 'PREMIUM', capabilities: ['reasoning'], latency: { expectedLatencyMs: 3000 } }), def({ providerId: 'b', modelId: 'fast-vision', capabilities: ['reasoning', 'vision'], latency: { expectedLatencyMs: 100 } }), def({ providerId: 'c', modelId: 'expensive', qualityTier: 'PREMIUM', capabilities: ['reasoning', 'vision'], cost: { costPerInputUnit: 2, costPerOutputUnit: 2, currency: 'TEST' } })]; const r = new ModelRegistry(ms, ms.map((m) => success(m.providerId, m.modelId))); const o = { preferredCapabilities: ['vision'], latencySensitive: true, maxCost: 0.5 }; assert.equal(routeModel(req(o), r, pol()).selectedModelId, 'fast-vision'); assert.deepEqual(routeModel(req(o), r, pol()), routeModel(req(o), r, pol())); });
test('quality and provider/model allowlists constrain eligibility', () => { const a = def({ providerId: 'a', modelId: 'a', qualityTier: 'BASIC' }); const b = def({ providerId: 'b', modelId: 'b', qualityTier: 'PREMIUM' }); const r = new ModelRegistry([a, b], [success('a', 'a'), success('b', 'b')]); assert.equal(routeModel(req({ minimumQualityTier: 'PREMIUM' }), r, pol()).selectedModelId, 'b'); assert.equal(routeModel(req(), r, pol({ allowedProviderIds: ['a'], allowedModelIds: ['a'] })).selectedModelId, 'a'); });
test('organization-owned models cannot cross organizations', () => { const d = def({ providerId: 'b', modelId: 'b', organizationId: 'org-b' }); const x = new ModelRuntime(new ModelRegistry([d], [success('b', 'b')])).run(req({ organizationId: 'org-a' }), pol()); assert.equal(x.status, 'FAILURE'); assert.equal(x.failure.code, 'NO_ELIGIBLE_MODEL'); });
test('missing organization context is rejected by routing policy', () => { const x = new ModelRuntime(new ModelRegistry([def()], [success('p', 'm')])).run(req({ organizationId: undefined }), pol()); assert.equal(x.status, 'FAILURE'); assert.equal(x.failure.code, 'ROUTING_POLICY_REJECTED'); });
test('provider failure and timeout remain structured failures', () => { for (const code of ['PROVIDER_FAILURE', 'TIMEOUT'] as const) { const d = def(); const x = new ModelRuntime(new ModelRegistry([d], [failure('p', 'm', code)])).run(req({ allowFallback: false }), pol({ allowFallback: false })); assert.equal(x.status, 'FAILURE'); assert.equal(x.failure.code, code); } });
test('fallback succeeds only among eligible candidates and preserves attempts', () => { const a = def({ providerId: 'a', modelId: 'a', qualityTier: 'PREMIUM' }); const b = def({ providerId: 'b', modelId: 'b' }); const x = new ModelRuntime(new ModelRegistry([a, b], [failure('a', 'a', 'PROVIDER_UNAVAILABLE'), success('b', 'b')])).run(req(), pol()); assert.equal(x.status, 'SUCCESS'); assert.equal(x.response.modelId, 'b'); assert.deepEqual(x.attemptedModels.map((m) => m.modelId), ['a', 'b']); });
test('fallback exhaustion fails closed and cannot bypass policy', () => { const a = def({ providerId: 'a', modelId: 'a', qualityTier: 'PREMIUM' }); const b = def({ providerId: 'b', modelId: 'b' }); const r = new ModelRegistry([a, b], [failure('a', 'a', 'PROVIDER_FAILURE'), success('b', 'b')]); const x = new ModelRuntime(r).run(req(), pol({ allowedProviderIds: ['a'] })); assert.equal(x.status, 'FAILURE'); assert.equal(x.failure.code, 'FALLBACK_EXHAUSTED'); assert.equal(x.attemptedModels.length, 1); });
test('fallback is disabled when request disallows it', () => { const d = def(); const x = new ModelRuntime(new ModelRegistry([d], [failure('p', 'm', 'PROVIDER_FAILURE')])).run(req({ allowFallback: false }), pol()); assert.equal(x.status, 'FAILURE'); assert.equal(x.failure.code, 'PROVIDER_FAILURE'); });
test('provenance is preserved from request through routing and response', () => { const x = new ModelRuntime(new ModelRegistry([def()], [success('p', 'm')])).run(req({ requestId: 'rp', correlationId: 'cp' }), pol()); assert.equal(x.status, 'SUCCESS'); assert.equal(x.routing.provenance.requestId, 'rp'); assert.equal(x.response.requestId, 'rp'); assert.equal(x.response.correlationId, 'cp'); });
test('provenance mismatch fails closed', () => { const d = def(); const bad: ModelProvider = { providerId: 'p', modelId: 'm', generate(input) { return { ...success('p', 'm').generate(input), providerId: 'wrong' }; } }; const x = new ModelRuntime(new ModelRegistry([d], [bad])).run(req(), pol()); assert.equal(x.status, 'FAILURE'); assert.equal(x.failure.code, 'PROVENANCE_MISMATCH'); });
test('routing result has no authorization or execution authority', () => { const x = routeModel(req(), new ModelRegistry([def()], [success('p', 'm')]), pol()); for (const key of ['grantedPermissions', 'grantedCapabilities', 'approvalGranted', 'workerId', 'credentialId', 'execute', 'dispatch', 'jobId']) assert.equal(key in x, false); });
test('runtime has no credential, execution, or dispatch operation and model output remains data', () => { const r = new ModelRuntime(new ModelRegistry([def()], [success('p', 'm')])); assert.equal('getCredential' in r, false); assert.equal('execute' in r, false); assert.equal('dispatch' in r, false); const x = r.run(req(), pol()); assert.equal(x.status, 'SUCCESS'); assert.deepEqual(x.response.output, { kind: 'test-output', input: { objective: 'test' } }); });
test('invalid definitions and requests fail closed', () => { assert.throws(() => new ModelRegistry([def({ context: { maxInputUnits: 0 } })], []), /maxInputUnits/); const x = new ModelRuntime(new ModelRegistry([def()], [success('p', 'm')])).run(req({ requestId: '' }), pol()); assert.equal(x.status, 'FAILURE'); assert.equal(x.failure.code, 'INVALID_REQUEST'); });
test('unregistered eligible provider is unavailable rather than invented', () => { const x = new ModelRuntime(new ModelRegistry([def()], [])).run(req({ allowFallback: false }), pol({ allowFallback: false })); assert.equal(x.status, 'FAILURE'); assert.equal(x.failure.code, 'MODEL_UNAVAILABLE'); });
