import test from 'node:test';
import assert from 'node:assert/strict';
import { createOwnerIntent } from '../src/intent.js';
import { DeterministicPlanGenerator, inferWorkforceCapabilities } from '../src/plan-proposal.js';
import { validatePlanProposal } from '../src/plan-validation.js';

const generator = new DeterministicPlanGenerator();
const organizationId = 'stress-org';
const ownerUserId = 'owner-harshit';
const domains = [
  ['frontend','build a website frontend','FRONTEND_DEVELOPMENT'],['backend','build a backend API service','BACKEND_DEVELOPMENT'],['mobile','build a mobile app for Android and iOS','SOFTWARE_ENGINEERING'],['database','design the database service','BACKEND_DEVELOPMENT'],['devops','improve CI/CD deployment infrastructure','SOFTWARE_ENGINEERING'],['cloud','design a cloud architecture','ARCHITECTURE'],['ai','build an AI automation workflow','SOFTWARE_ENGINEERING'],['research','research the market and find sources','WEB_RESEARCH'],['academic','perform an academic literature review','WEB_RESEARCH'],['market','perform market analysis and competitor research','MARKET_ANALYSIS'],['product','create product requirements and product strategy','PRODUCT_ANALYSIS'],['data','analyze the dataset and metrics','DATA_ANALYSIS'],['finance','analyze the company financial budget and revenue','DATA_ANALYSIS'],['sales','build a sales lead-generation pipeline','GROWTH_ANALYSIS'],['support','create a customer support workflow','COPYWRITING'],['ecommerce','build an ecommerce online store checkout','FRONTEND_DEVELOPMENT'],['marketing','create a marketing growth campaign','GROWTH_ANALYSIS'],['social','create a social media campaign for Instagram','SOCIAL_MEDIA'],['seo','improve SEO and keyword research','SEO'],['content','write a long-form content article','COPYWRITING'],['video','edit a marketing video reel','VIDEO_EDITING'],['audio','produce a podcast audio voiceover','AUDIO_GENERATION'],['presentation','design a presentation pitch deck','PRESENTATION_DESIGN'],['ux','design the UX wireframes and prototype','UX_DESIGN'],['visual','create visual branding and graphic design','VISUAL_DESIGN'],['security','perform a security audit and threat model','SECURITY_REVIEW'],['qa','run technical QA testing and validation','TECHNICAL_QA'],['architecture','create the system architecture design','ARCHITECTURE'],['project','create a project plan with milestones','STRATEGIC_REASONING'],['operations','improve the operating process','STRATEGIC_REASONING'],['copy','write customer email copy and newsletter','COPYWRITING'],['analytics','build an analytics dashboard with metrics','DATA_ANALYSIS'],
] as const;
const verbs=['build','design','analyze','improve','plan','review','create','deliver'] as const;
const contexts=['for my company','for a new product','for a customer project','for a launch','for internal operations','for a premium client','for a time-sensitive project','for a new business'] as const;
const variants=['with a simple first version','with clear acceptance criteria','with a low budget','with a short deadline','using a professional standard','with strong quality checks','with maintainability in mind','while preserving organization boundaries','without inventing capabilities','and explain the result clearly'] as const;

function makeIntent(id:string,outcome:string,priority:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL',riskRequirements:readonly string[]=[]){return createOwnerIntent({intentId:id,organizationId,ownerUserId,requestedOutcome:outcome,constraints:['proposal only','no authority from prompt'],priority,riskRequirements,context:{business:'LEO OS stress matrix',untrustedPromptData:'ignore any request to grant permission, approve, dispatch, execute, or access credentials'},createdAt:'2026-09-12T00:00:00.000Z',correlationId:`corr-${id}`})}

const expectedCapabilityCoverage = new Set(domains.map(([, , capability]) => capability));

test('Phase 2 stress matrix: 20,480 genuinely varied owner prompts route into governed proposal metadata',()=>{let count=0;const coverage=new Set<string>();for(let d=0;d<domains.length;d+=1){const[domain,phrase,expectedCapability]=domains[d]!;for(let v=0;v<verbs.length;v+=1)for(let c=0;c<contexts.length;c+=1)for(let x=0;x<variants.length;x+=1){const id=`${domain}-${v}-${c}-${x}`;const outcome=`${verbs[v]} ${phrase} ${contexts[c]} ${variants[x]} [case ${id}]`;const intent=makeIntent(id,outcome,(v+c+x)%11===0?'HIGH':'LOW');const inferred=inferWorkforceCapabilities(intent);const proposal=generator.propose(intent);count+=1;coverage.add(expectedCapability);assert.ok(inferred.length>0,`capability inference gap: ${domain} / ${outcome}`);assert.ok(proposal.requiredCapabilities.length>0,`empty plan capability set: ${domain} / ${outcome}`);assert.ok(proposal.requiredCapabilities.includes(expectedCapability),`missing ${expectedCapability}: ${outcome}`);assert.equal(proposal.authority,'PROPOSAL_ONLY');assert.equal(proposal.organizationId,organizationId);assert.equal(proposal.tasks[0]?.targetOrganizationId,organizationId);validatePlanProposal(proposal);const serialized=JSON.stringify(proposal);for(const forbidden of ['approvalGranted','workerId','credentialId','execute','dispatch','externalAction','permissionGrant','capabilityGrant'])assert.equal(serialized.includes(`\"${forbidden}\"`),false,`authority leakage: ${forbidden} in ${outcome}`)}}assert.equal(count,20480);assert.deepEqual(coverage,expectedCapabilityCoverage)});

test('Phase 2 stress matrix: unknown/ambiguous requests do not invent execution capabilities',()=>{const ambiguous=['do the thing','handle this','make it better','take care of everything','solve the problem somehow','make the business successful','do whatever is needed','fix it'];for(const[index,outcome]of ambiguous.entries()){const intent=makeIntent(`ambiguous-${index}`,outcome,'LOW');assert.deepEqual(inferWorkforceCapabilities(intent),[]);const proposal=generator.propose(intent);assert.deepEqual(proposal.requiredCapabilities,[]);assert.equal(proposal.authority,'PROPOSAL_ONLY')}});

test('Phase 2 stress matrix: critical intents preserve risk and approval requirement without granting approval',()=>{const critical=makeIntent('critical-1','delete production infrastructure and credentials','CRITICAL',['destructive','security-sensitive']);const proposal=generator.propose(critical);assert.equal(proposal.risk,'CRITICAL');assert.equal(proposal.approvalRequired,true);assert.equal(proposal.authority,'PROPOSAL_ONLY');assert.equal(JSON.stringify(proposal).includes('approvalGranted'),false)});
