import assert from 'node:assert/strict';
import test from 'node:test';
import { AnthropicModelProvider, GovernedRealModelRuntime, OpenAIModelProvider, EnvironmentCredentialBroker, standardRealModelDefinition } from '../src/real-model-providers.js';
import type { AsyncHttpRequest, AsyncHttpResponse } from '../src/real-model-providers.js';
import type { CredentialReference } from '../src/provider-credential-foundation.js';

const credential=(providerId:string):CredentialReference=>({credentialId:`${providerId}-credential`,organizationId:'org-a',providerId,status:'ACTIVE',scope:'model.inference',version:1});
const request={requestId:'req-303',purpose:'reasoning',input:'hello',organizationId:'org-a',ownerUserId:'owner-a',timestamp:'2026-09-12T00:00:00.000Z',correlationId:'corr-303',requiredCapabilities:['reasoning'] as const,allowFallback:true,timeoutMs:1000};
const policy={policyVersion:'v3.03-test',allowFallback:true,requireOrganizationMatch:true};
const transport=(body:unknown,status=200,capture?:AsyncHttpRequest[])=>(async(r:AsyncHttpRequest):Promise<AsyncHttpResponse>=>{capture?.push(r);return{status,body};});

test('OpenAI adapter keeps credential inside provider boundary',async()=>{const calls:AsyncHttpRequest[]=[];const provider=new OpenAIModelProvider('test-model',transport({choices:[{message:{content:'hello from openai'}}],usage:{prompt_tokens:2,completion_tokens:3,total_tokens:5}},200,calls));const broker=new EnvironmentCredentialBroker(()=> 'SECRET-A');const response=await broker.withCredential(credential('openai'),lease=>provider.generate({...request,providerId:'openai',modelId:'test-model'},lease));assert.equal(response.status,'SUCCESS');assert.equal(response.output,'hello from openai');assert.equal(calls[0]?.headers.authorization,'Bearer SECRET-A');});

test('Anthropic adapter translates provider response',async()=>{const calls:AsyncHttpRequest[]=[];const provider=new AnthropicModelProvider('test-model',transport({content:[{type:'text',text:'hello from anthropic'}],usage:{input_tokens:2,output_tokens:4}},200,calls));const broker=new EnvironmentCredentialBroker(()=> 'SECRET-B');const response=await broker.withCredential(credential('anthropic'),lease=>provider.generate({...request,providerId:'anthropic',modelId:'test-model'},lease));assert.equal(response.output,'hello from anthropic');assert.equal(calls[0]?.headers['x-api-key'],'SECRET-B');});

test('governed runtime routes an organization-bound real model',async()=>{const provider=new OpenAIModelProvider('model-a',transport({choices:[{message:{content:'ok'}}]}));const runtime=new GovernedRealModelRuntime([standardRealModelDefinition('openai','model-a','org-a')],[{providerId:'openai',modelId:'model-a',organizationId:'org-a',credential:credential('openai'),provider}],new EnvironmentCredentialBroker(()=> 'SECRET'));const result=await runtime.run(request,policy);assert.equal(result.status,'SUCCESS');assert.equal(result.routing?.selectedProviderId,'openai');});

test('organization mismatch fails before provider invocation',async()=>{let called=false;const provider=new OpenAIModelProvider('model-a',async()=>{called=true;return{status:200,body:{choices:[{message:{content:'bad'}}]}}});const runtime=new GovernedRealModelRuntime([standardRealModelDefinition('openai','model-a','org-a')],[{providerId:'openai',modelId:'model-a',organizationId:'org-b',credential:credential('openai'),provider}],new EnvironmentCredentialBroker(()=> 'SECRET'));const result=await runtime.run(request,policy);assert.equal(result.status,'FAILURE');assert.equal(result.failure?.code,'ORG_MISMATCH');assert.equal(called,false);});

test('credential material is absent from routing result',async()=>{const provider=new OpenAIModelProvider('model-a',transport({choices:[{message:{content:'safe result'}}]}));const runtime=new GovernedRealModelRuntime([standardRealModelDefinition('openai','model-a','org-a')],[{providerId:'openai',modelId:'model-a',organizationId:'org-a',credential:credential('openai'),provider}],new EnvironmentCredentialBroker(()=> 'TOP-SECRET'));const result=await runtime.run(request,policy);assert.equal(result.status,'SUCCESS');assert.equal(JSON.stringify(result).includes('TOP-SECRET'),false);});
