import assert from 'node:assert/strict';
import test from 'node:test';
import { DeterministicToolAdapter, ToolGateway, ToolRegistry, type ControlPlaneWorkerBinding, type ToolDefinition, type ToolInvocationRequest } from '../src/index.js';

const worker: ControlPlaneWorkerBinding = { workerId:'worker-a', organizationId:'org-a', taskId:'task-a', delegationId:'delegation-a', roleId:'role-a', capabilities:['SOFTWARE_ENGINEERING','internal.execute'], context:{organization:true}, providerId:'provider.test', modelId:'model.test', risk:'LOW' };
const tool: ToolDefinition = { toolId:'internal.noop', organizationId:'org-a', capabilityId:'internal.execute', description:'deterministic internal tool', input:{name:'object',validate:v=>!!v&&typeof v==='object'}, output:{name:'object',validate:v=>!!v&&typeof v==='object'}, risk:'LOW', idempotent:true, requiredApproval:false, status:'AVAILABLE', provenance:'v3.02-test' };
function gateway(){const r=new ToolRegistry();r.register(tool,new DeterministicToolAdapter(tool.toolId,input=>({echo:input})));return new ToolGateway(r)}
function request(overrides:Partial<ToolInvocationRequest>={}):ToolInvocationRequest{return {toolId:tool.toolId,organizationId:'org-a',taskId:'task-a',workerId:'worker-a',capability:'internal.execute',input:{ok:true},correlationId:'corr-a',idempotencyKey:'idem-a',...overrides}}

test('authorized worker invokes typed tool',()=>{const result=gateway().invoke(request(),{worker,approvalValid:false});assert.equal(result.status,'SUCCESS')});
test('model-like caller without worker binding is denied',()=>{const result=gateway().invoke(request({workerId:'model-selected-worker'}),{worker,approvalValid:false});assert.equal(result.status,'FAILURE');if(result.status==='FAILURE')assert.equal(result.code,'AUTHORIZATION_DENIED')});
test('cross-organization request is denied',()=>{const result=gateway().invoke(request({organizationId:'org-b'}),{worker,approvalValid:false});assert.equal(result.status,'FAILURE');if(result.status==='FAILURE')assert.equal(result.code,'ORG_MISMATCH')});
test('missing capability is denied',()=>{const result=gateway().invoke(request({capability:'WEB_RESEARCH'}),{worker,approvalValid:false});assert.equal(result.status,'FAILURE');if(result.status==='FAILURE')assert.equal(result.code,'CAPABILITY_MISSING')});
test('malformed typed input is rejected',()=>{const result=gateway().invoke(request({input:'not-an-object'}),{worker,approvalValid:false});assert.equal(result.status,'FAILURE');if(result.status==='FAILURE')assert.equal(result.code,'MALFORMED_INPUT')});
test('high-risk tool requires approval',()=>{const r=new ToolRegistry();r.register({...tool,risk:'HIGH',requiredApproval:true},new DeterministicToolAdapter(tool.toolId,()=>({ok:true})));const result=new ToolGateway(r).invoke(request(),{worker:{...worker,risk:'HIGH'},approvalValid:false});assert.equal(result.status,'FAILURE');if(result.status==='FAILURE')assert.equal(result.code,'APPROVAL_REQUIRED')});
test('critical tool is denied even with approval',()=>{const r=new ToolRegistry();r.register({...tool,risk:'CRITICAL'},new DeterministicToolAdapter(tool.toolId,()=>({ok:true})));const result=new ToolGateway(r).invoke(request(),{worker:{...worker,risk:'CRITICAL'},approvalValid:true});assert.equal(result.status,'FAILURE');if(result.status==='FAILURE')assert.equal(result.code,'AUTHORIZATION_DENIED')});
test('duplicate idempotency key returns the original result',()=>{const g=gateway();const first=g.invoke(request(),{worker,approvalValid:false});const second=g.invoke(request(),{worker,approvalValid:false});assert.deepEqual(second,first)});
test('disabled tool fails closed',()=>{const r=new ToolRegistry();r.register({...tool,status:'DISABLED'},new DeterministicToolAdapter(tool.toolId,()=>({ok:true})));const result=new ToolGateway(r).invoke(request(),{worker,approvalValid:false});assert.equal(result.status,'FAILURE');if(result.status==='FAILURE')assert.equal(result.code,'TOOL_DISABLED')});
test('tool output cannot smuggle authority fields',()=>{const r=new ToolRegistry();r.register(tool,new DeterministicToolAdapter(tool.toolId,()=>({execute:true})));const result=new ToolGateway(r).invoke(request(),{worker,approvalValid:false});assert.equal(result.status,'FAILURE');if(result.status==='FAILURE')assert.equal(result.code,'OUTPUT_INVALID')});
