import test from 'node:test';
import assert from 'node:assert/strict';
import { ToolGateway, ToolRegistry, type ToolDefinition } from '../src/tool-adapters.js';
import { DeterministicCredentialBroker, type CredentialReference } from '../src/provider-credential-foundation.js';
import { buildYouTubePublicationProposal, createYouTubeToolRequest, assertVerifiedMedia, classifyYouTubeRisk, YouTubePublisherAdapter, YOUTUBE_CAPABILITY, YOUTUBE_TOOL_ID, type YouTubeChannelBinding, type YouTubeApiTransport } from '../src/youtube-creator.js';
import type { MediaAsset } from '../src/media-production.js';
import type { ControlPlaneWorkerBinding } from '../src/delegation.js';

const credential:CredentialReference={credentialId:'cred-1',organizationId:'org-1',providerId:'youtube',status:'ACTIVE',scope:'youtube.publish',version:1};
const channel:YouTubeChannelBinding={channelId:'channel-1',organizationId:'org-1',credential,status:'ACTIVE'};
const media:MediaAsset={assetId:'asset-1',organizationId:'org-1',taskId:'task-1',correlationId:'corr-1',parentAssetIds:[],mediaType:'VIDEO',format:'mp4',mimeType:'video/mp4',createdAt:new Date().toISOString(),producerId:'v304',contentHash:'sha256:ok',storageRef:'authoritative://asset-1',validationStatus:'VALID',status:'VERIFIED',metadata:{}};
const worker:ControlPlaneWorkerBinding={workerId:'worker-1',organizationId:'org-1',taskId:'task-1',delegationId:'delegation-1',roleId:'creator',capabilities:[YOUTUBE_CAPABILITY],context:{organization:'org-1',businessId:'b',projectId:'p',departmentId:'d',workingContext:'youtube'},providerId:'internal',modelId:'model',risk:'HIGH'};
const metadata={title:'Test video',description:'desc',tags:['test'],visibility:'public' as const};

function setup(){const broker=new DeterministicCredentialBroker(new Map([['cred-1','SECRET']]));const transport:YouTubeApiTransport={publish:({channelId})=>({videoId:'video-1',publicationId:'pub-1',channelId,visibility:'public'}),verify:({channelId})=>({videoId:'video-1',publicationId:'pub-1',channelId,visibility:'public'})};const adapter=new YouTubePublisherAdapter([channel],broker,transport);const registry=new ToolRegistry();const def:ToolDefinition={toolId:YOUTUBE_TOOL_ID,organizationId:'org-1',capabilityId:YOUTUBE_CAPABILITY,description:'Governed YouTube publication',input:{name:'youtube-publication',validate:v=>!!v&&typeof v==='object'},output:{name:'youtube-result',validate:v=>!!v&&typeof v==='object'},risk:'HIGH',idempotent:true,requiredApproval:true,provenance:'v3.05'};registry.register(def,adapter);return {gateway:new ToolGateway(registry),adapter};}

test('requires verified V3.04 media',()=>assert.throws(()=>assertVerifiedMedia({...media,status:'PRODUCED',validationStatus:'UNVALIDATED'})));
test('builds proposal only from verified media and keeps authority proposal-only',()=>{const p=buildYouTubePublicationProposal({channel,media,metadata,correlationId:'corr-1',idempotencyKey:'pub-1',risk:'HIGH',approvalRequired:true},'owner-1');assert.equal(p.authority,'PROPOSAL_ONLY');assert.equal(p.channelId,'channel-1');assert.equal(p.mediaAssetId,'asset-1');assert.equal(p.approvalRequired,true);});
test('public visibility is high risk',()=>assert.equal(classifyYouTubeRisk('public'),'HIGH'));
test('wrong organization worker is denied before tool call',()=>{const {gateway}=setup();const p=buildYouTubePublicationProposal({channel,media,metadata,correlationId:'corr-2',idempotencyKey:'pub-2',risk:'HIGH',approvalRequired:true},'owner-1');const bad={...worker,organizationId:'org-2'};assert.throws(()=>createYouTubeToolRequest({channel,media,metadata,correlationId:'corr-2',idempotencyKey:'pub-2',risk:'HIGH',approvalRequired:true},bad,p));void gateway;});
test('approval is required and is not inferred from proposal metadata',()=>{const {gateway}=setup();const p=buildYouTubePublicationProposal({channel,media,metadata,correlationId:'corr-3',idempotencyKey:'pub-3',risk:'HIGH',approvalRequired:true},'owner-1');const req=createYouTubeToolRequest({channel,media,metadata,correlationId:'corr-3',idempotencyKey:'pub-3',risk:'HIGH',approvalRequired:true},worker,p);const result=gateway.invoke(req,{worker,approvalValid:false});assert.equal(result.status,'FAILURE');if(result.status==='FAILURE')assert.equal(result.code,'APPROVAL_REQUIRED');});
test('authorized worker reaches YouTube adapter through ToolGateway',()=>{const {gateway}=setup();const input={channel,media,metadata,correlationId:'corr-4',idempotencyKey:'pub-4',risk:'HIGH' as const,approvalRequired:true};const p=buildYouTubePublicationProposal(input,'owner-1');const req=createYouTubeToolRequest(input,worker,p);const result=gateway.invoke(req,{worker,approvalValid:true});assert.equal(result.status,'SUCCESS');});
test('idempotency prevents duplicate publication execution',()=>{const {gateway}=setup();const input={channel,media,metadata,correlationId:'corr-5',idempotencyKey:'pub-5',risk:'HIGH' as const,approvalRequired:true};const p=buildYouTubePublicationProposal(input,'owner-1');const req=createYouTubeToolRequest(input,worker,p);const first=gateway.invoke(req,{worker,approvalValid:true});const second=gateway.invoke(req,{worker,approvalValid:true});assert.deepEqual(second,first);});
test('credential reference cannot cross channel binding',()=>{const {gateway}=setup();const other={...channel,credential:{...credential,credentialId:'cred-other'}};const input={channel:other,media,metadata,correlationId:'corr-6',idempotencyKey:'pub-6',risk:'HIGH' as const,approvalRequired:true};const p=buildYouTubePublicationProposal(input,'owner-1');const req=createYouTubeToolRequest(input,worker,p);const result=gateway.invoke(req,{worker,approvalValid:true});assert.equal(result.status,'FAILURE');});
