import type { Prisma, PrismaClient, ApprovalStatus } from '@prisma/client';
import { AUDIT_EVENTS, sanitizeAuditMetadata, type AuditEventInput } from './audit.js';
export const APPROVAL_TRANSITIONS: Record<ApprovalStatus, readonly ApprovalStatus[]> = { PENDING:['APPROVED','REJECTED','EXPIRED','CANCELLED'], APPROVED:[], REJECTED:[], EXPIRED:[], CANCELLED:[] };
export interface CreateApprovalInput { organizationId:string; jobId?:string; requesterId?:string; requesterAgentId?:string; targetResourceType?:string; targetResourceId?:string; action:string; actionFingerprint:string; policyVersion:string; riskLevel:Prisma.ApprovalCreateInput['riskLevel']; reason:string; evidence:Record<string,unknown>; estimatedCost?:number; expiresAt?:Date; }
const auditData=(organizationId:string,actorId:string|undefined,actorType:Prisma.AuditEventCreateInput['actorType'],eventType:AuditEventInput['eventType'],resourceId:string,action:string,result:Prisma.AuditEventCreateInput['result'],metadata:unknown={})=>({organization:{connect:{id:organizationId}},actor:actorId?{connect:{id:actorId}}:undefined,actorType,eventType,resourceType:'Approval',resourceId,action,result,metadata:sanitizeAuditMetadata(metadata) as Prisma.InputJsonValue});
const isSerializationConflict=(error:unknown)=>typeof error==='object'&&error!==null&&'code' in error&&(error as {code?:unknown}).code==='P2034';
export class ApprovalRepository {
 constructor(private readonly db:PrismaClient){}
 async create(input:CreateApprovalInput,audit:Omit<AuditEventInput,'eventType'>){return this.db.$transaction(async tx=>{if(input.jobId){const job=await tx.job.findFirst({where:{id:input.jobId,organizationId:input.organizationId}});if(!job)return null;}const item=await tx.approval.create({data:{organization:{connect:{id:input.organizationId}},job:input.jobId?{connect:{id:input.jobId}}:undefined,requester:input.requesterId?{connect:{id:input.requesterId}}:undefined,requesterAgentId:input.requesterAgentId,targetResourceType:input.targetResourceType,targetResourceId:input.targetResourceId,action:input.action,actionFingerprint:input.actionFingerprint,policyVersion:input.policyVersion,riskLevel:input.riskLevel,reason:input.reason,evidence:sanitizeAuditMetadata(input.evidence) as Prisma.InputJsonValue,estimatedCost:input.estimatedCost,expiresAt:input.expiresAt}});await tx.auditEvent.create({data:{organization:{connect:{id:input.organizationId}},actor:audit.actorId?{connect:{id:audit.actorId}}:undefined,actorType:audit.actorType,eventType:AUDIT_EVENTS.APPROVAL_CREATED,resourceType:'Approval',resourceId:item.id,action:audit.action,result:audit.result,metadata:sanitizeAuditMetadata(audit.metadata??{}) as Prisma.InputJsonValue}});return item;},{isolationLevel:'Serializable'});}
 list(organizationId:string){return this.db.approval.findMany({where:{organizationId},orderBy:{createdAt:'desc'}})}
 get(organizationId:string,id:string){return this.db.approval.findFirst({where:{organizationId,id}})}
 private async applyDecisionToJob(tx:Prisma.TransactionClient,approval:{jobId:string|null},organizationId:string,next:ApprovalStatus,now:Date){if(!approval.jobId)return;const job=await tx.job.findFirst({where:{id:approval.jobId,organizationId}});if(!job)return;if(next==='APPROVED'&&job.status==='WAITING_APPROVAL'){await tx.job.update({where:{id:job.id},data:{status:'RETRY_QUEUED',workerId:null,nextRetryAt:now,completedAt:null,failureCode:null,failureMessage:null,failureRetryable:null}});if(job.workflowId){const workflow=await tx.workflow.findFirst({where:{id:job.workflowId,organizationId}});if(workflow&&workflow.status==='WAITING_APPROVAL')await tx.workflow.update({where:{id:workflow.id},data:{status:'RUNNING',currentState:'RUNNING',currentJobId:job.id}})}}else if((next==='REJECTED'||next==='EXPIRED'||next==='CANCELLED')&&job.status==='WAITING_APPROVAL'){await tx.job.update({where:{id:job.id},data:{status:'FAILED',workerId:null,leaseExpiresAt:null,completedAt:now,failureCode:`APPROVAL_${next}`,failureMessage:`Approval was ${next.toLowerCase()}.`,failureRetryable:false}});if(job.workflowId){const workflow=await tx.workflow.findFirst({where:{id:job.workflowId,organizationId}});if(workflow&&['WAITING_APPROVAL','RUNNING'].includes(workflow.status)){await tx.workflow.update({where:{id:workflow.id},data:{status:'FAILED',currentState:'FAILED',currentJobId:null,failureCode:`APPROVAL_${next}`,failureMessage:`Approval was ${next.toLowerCase()}.`,completedAt:now}})}}}}
 async decide(organizationId:string,id:string,next:ApprovalStatus,decidingUserId:string,audit:Omit<AuditEventInput,'eventType'>){for(let attempt=0;attempt<3;attempt++){try{return await this.db.$transaction(async tx=>{const current=await tx.approval.findFirst({where:{organizationId,id}});if(!current)return{kind:'missing' as const};if(current.requesterId===decidingUserId)return{kind:'self_approval' as const};const now=new Date();if(current.expiresAt&&current.expiresAt<=now&&current.status==='PENDING'){await tx.approval.update({where:{id},data:{status:'EXPIRED',decidedAt:now}});await this.applyDecisionToJob(tx,current,organizationId,'EXPIRED',now);await tx.auditEvent.create({data:auditData(organizationId,audit.actorId,audit.actorType,AUDIT_EVENTS.APPROVAL_EXPIRED,id,'expire',audit.result,audit.metadata)});return{kind:'expired' as const};}if(!APPROVAL_TRANSITIONS[current.status].includes(next))return{kind:'conflict' as const,status:current.status};const updated=await tx.approval.update({where:{id},data:{status:next,decidedAt:now,decidedBy:decidingUserId}});await this.applyDecisionToJob(tx,current,organizationId,next,now);const eventType=next==='APPROVED'?AUDIT_EVENTS.APPROVAL_APPROVED:next==='REJECTED'?AUDIT_EVENTS.APPROVAL_REJECTED:AUDIT_EVENTS.APPROVAL_CANCELLED;await tx.auditEvent.create({data:auditData(organizationId,decidingUserId,'USER',eventType,id,next.toLowerCase(),audit.result,audit.metadata)});return{kind:'updated' as const,item:updated};},{isolationLevel:'Serializable'});}catch(error){if(!isSerializationConflict(error)||attempt===2)throw error;}}throw new Error('Unreachable');}
 async consume(organizationId:string,id:string,fingerprint:string,workerId:string,audit:AuditEventInput){for(let attempt=0;attempt<3;attempt++){try{return await this.db.$transaction(async tx=>{const item=await tx.approval.findFirst({where:{organizationId,id}});if(!item)return{kind:'missing' as const};if(item.status!=='APPROVED'||item.consumedAt)return{kind:'conflict' as const};if(item.expiresAt&&item.expiresAt<=new Date())return{kind:'expired' as const};if(item.actionFingerprint!==fingerprint||item.requesterAgentId!==workerId)return{kind:'binding_mismatch' as const};const updated=await tx.approval.updateMany({where:{organizationId,id,status:'APPROVED',consumedAt:null,actionFingerprint:fingerprint,requesterAgentId:workerId},data:{consumedAt:new Date(),consumedFingerprint:fingerprint}});if(updated.count!==1)return{kind:'conflict' as const};await tx.auditEvent.create({data:{organization:{connect:{id:organizationId}},actorType:'AGENT',eventType:AUDIT_EVENTS.EXECUTION_APPROVED,resourceType:'Approval',resourceId:id,action:'consume',result:'SUCCESS',metadata:sanitizeAuditMetadata(audit.metadata??{}) as Prisma.InputJsonValue}});return{kind:'consumed' as const};},{isolationLevel:'Serializable'});}catch(error){if(!isSerializationConflict(error)||attempt===2)throw error;}}throw new Error('Unreachable');}
}
