import type { Prisma, PrismaClient } from '@prisma/client';
import { AUDIT_EVENTS, type AuditEventInput, sanitizeAuditMetadata } from './audit.js';
import { canTransitionJob, retryDecision, type JobStatus } from '@founder-os/core';
export interface CreateJobInput { organizationId:string; objectiveId?:string; taskId?:string; workflowId?:string; priority?:number; maxAttempts?:number; resumableState?:Record<string,unknown>; metadata?:Record<string,unknown>; }
export interface JobFailure { code:string; message:string; retryable:boolean; }
function auditData(input:AuditEventInput,eventType:AuditEventInput['eventType'],resourceId:string):Prisma.AuditEventCreateInput{return{organization:{connect:{id:input.organizationId}},actor:input.actorId?{connect:{id:input.actorId}}:undefined,actorType:input.actorType,eventType,resourceType:'Job',resourceId,action:input.action,result:input.result,metadata:sanitizeAuditMetadata(input.metadata??{}) as Prisma.InputJsonValue};}
export class JobRepository {
 constructor(private readonly db:PrismaClient){}
 list(organizationId:string){return this.db.job.findMany({where:{organizationId},orderBy:[{priority:'desc'},{createdAt:'asc'}]});}
 get(organizationId:string,id:string){return this.db.job.findFirst({where:{organizationId,id},include:{checkpoints:{orderBy:{version:'desc'},take:1}}});}
 async create(input:CreateJobInput,audit:AuditEventInput){return this.db.$transaction(async tx=>{ if(input.objectiveId){const o=await tx.objective.findFirst({where:{id:input.objectiveId,organizationId},select:{id:true}});if(!o)return null;} if(input.taskId){const t=await tx.task.findFirst({where:{id:input.taskId,objective:{organizationId}},select:{id:true}});if(!t)return null;} if(input.workflowId){const w=await tx.workflow.findFirst({where:{id:input.workflowId,organizationId},select:{id:true}});if(!w)return null;} const item=await tx.job.create({data:{organization:{connect:{id:input.organizationId}},objective:input.objectiveId?{connect:{id:input.objectiveId}}:undefined,task:input.taskId?{connect:{id:input.taskId}}:undefined,workflow:input.workflowId?{connect:{id:input.workflowId}}:undefined,priority:input.priority??0,maxAttempts:input.maxAttempts??3,resumableState:input.resumableState??{},metadata:input.metadata??{}}});await tx.auditEvent.create({data:auditData(audit,AUDIT_EVENTS.JOB_CREATED,item.id)});return item;},{isolationLevel:'Serializable'});}
 async claim(organizationId:string,id:string,workerId:string,leaseMs:number,audit:AuditEventInput,now=new Date()){if(!workerId.trim())throw new Error('workerId required');if(!Number.isFinite(leaseMs)||leaseMs<=0)throw new Error('leaseMs invalid');const lease=new Date(now.getTime()+leaseMs);return this.db.$transaction(async tx=>{const item=await tx.job.findFirst({where:{organizationId,id}});if(!item)return{kind:'missing' as const};if(item.status!=='QUEUED'&&item.status!=='RETRY_QUEUED')return{kind:'conflict' as const,status:item.status};if(item.nextRetryAt&&item.nextRetryAt>now)return{kind:'not_ready' as const};const result=await tx.job.updateMany({where:{organizationId,id,status:item.status,nextRetryAt:item.status==='RETRY_QUEUED'?{lte:now}:undefined},data:{status:'CLAIMED',workerId,attemptNumber:{increment:1},leaseExpiresAt:lease,lastHeartbeatAt:now}});if(result.count!==1)return{kind:'conflict' as const,status:item.status};await tx.auditEvent.create({data:auditData(audit,AUDIT_EVENTS.JOB_CLAIMED,id)});return{kind:'claimed' as const,leaseExpiresAt:lease};},{isolationLevel:'Serializable'});}
 async transition(organizationId:string,id:string,from:JobStatus,to:JobStatus,workerId:string|undefined,audit:AuditEventInput,now=new Date()){return this.db.$transaction(async tx=>{const item=await tx.job.findFirst({where:{organizationId,id}});if(!item)return{kind:'missing' as const};if(item.status!==from||!canTransitionJob(from,to))return{kind:'conflict' as const,status:item.status};if(workerId&&item.workerId!==workerId)return{kind:'not_owner' as const};const data:Prisma.JobUpdateInput={status:to};if(to==='RUNNING')data.startedAt=now;if(to==='SUCCEEDED'||to==='FAILED'||to==='CANCELLED'){data.completedAt=now;data.leaseExpiresAt=null;data.workerId=null;}if(to==='RETRY_QUEUED')data.workerId=null;await tx.job.update({where:{id},data});const event=to==='RUNNING'?AUDIT_EVENTS.JOB_STARTED:to==='SUCCEEDED'?AUDIT_EVENTS.JOB_SUCCEEDED:to==='FAILED'?AUDIT_EVENTS.JOB_FAILED:to==='CANCELLED'?AUDIT_EVENTS.JOB_CANCELLED:to==='RETRY_QUEUED'?AUDIT_EVENTS.JOB_RETRY_SCHEDULED:AUDIT_EVENTS.JOB_RESUMED;await tx.auditEvent.create({data:auditData(audit,event,id)});return{kind:'updated' as const};},{isolationLevel:'Serializable'});}
 async heartbeat(organizationId:string,id:string,workerId:string,leaseMs:number,now=new Date()){const lease=new Date(now.getTime()+leaseMs);const result=await this.db.job.updateMany({where:{organizationId,id,workerId,status:{in:['CLAIMED','RUNNING']},leaseExpiresAt:{gt:now}},data:{lastHeartbeatAt:now,leaseExpiresAt:lease}});return result.count===1;}
 async fail(organizationId:string,id:string,workerId:string,failure:JobFailure,audit:AuditEventInput,now=new Date()){return this.db.$transaction(async tx=>{const item=await tx.job.findFirst({where:{organizationId,id}});if(!item)return{kind:'missing' as const};if(item.workerId!==workerId||!['CLAIMED','RUNNING'].includes(item.status))return{kind:'conflict' as const,status:item.status};const decision=retryDecision(item.attemptNumber,item.maxAttempts,failure.retryable,now);const data:Prisma.JobUpdateInput={status:decision.status,failureCode:failure.code,failureMessage:sanitizeAuditMetadata(failure.message) as string,failureRetryable:failure.retryable,workerId:null,leaseExpiresAt:null,nextRetryAt:decision.nextRetryAt??null,completedAt:decision.status==='FAILED'?now:null};await tx.job.update({where:{id},data});await tx.auditEvent.create({data:auditData(audit,decision.status==='FAILED'?AUDIT_EVENTS.JOB_FAILED:AUDIT_EVENTS.JOB_RETRY_SCHEDULED,id)});return{kind:'updated' as const,status:decision.status};},{isolationLevel:'Serializable'});}
 async recoverStale(organizationId:string,id:string,audit:AuditEventInput,now=new Date()){return this.db.$transaction(async tx=>{const item=await tx.job.findFirst({where:{organizationId,id}});if(!item||!['CLAIMED','RUNNING'].includes(item.status)||!item.leaseExpiresAt||item.leaseExpiresAt>now)return{kind:'not_stale' as const};const decision=retryDecision(item.attemptNumber,item.maxAttempts,true,now);await tx.job.update({where:{id},data:{status:decision.status,failureCode:'LEASE_EXPIRED',failureMessage:'Worker lease expired.',failureRetryable:true,workerId:null,leaseExpiresAt:null,nextRetryAt:decision.nextRetryAt??null,completedAt:decision.status==='FAILED'?now:null}});await tx.auditEvent.create({data:auditData(audit,AUDIT_EVENTS.JOB_STALE_LEASE_RECOVERED,id)});return{kind:'recovered' as const,status:decision.status};},{isolationLevel:'Serializable'});}
 async checkpoint(organizationId:string,id:string,state:Record<string,unknown>,workerId:string,audit:AuditEventInput){return this.db.$transaction(async tx=>{const job=await tx.job.findFirst({where:{organizationId,id}});if(!job)return{kind:'missing' as const};if(job.workerId!==workerId||!['CLAIMED','RUNNING'].includes(job.status))return{kind:'not_owner' as const};const latest=await tx.checkpoint.findFirst({where:{organizationId,jobId:id},orderBy:{version:'desc'},select:{version:true}});const version=(latest?.version??0)+1;const clean=sanitizeAuditMetadata(state) as Prisma.InputJsonValue;const cp=await tx.checkpoint.create({data:{organization:{connect:{id:organizationId}},job:{connect:{id}},version,state:clean}});await tx.job.update({where:{id},data:{resumableState:clean}});await tx.auditEvent.create({data:auditData(audit,AUDIT_EVENTS.JOB_CHECKPOINT_CREATED,id)});return{kind:'created' as const,checkpoint:cp};},{isolationLevel:'Serializable'});}
}
