import type { ObjectiveStatus, Priority, RiskLevel } from '@founder-os/core';
import type { PrismaClient, TaskStatus, RiskLevel as DbRiskLevel } from '@prisma/client';
import { validateTaskGraph, type TaskGraph } from '@founder-os/core';

export interface CreateObjectiveInput { organizationId:string; title:string; description:string; createdBy:string; priority:Priority; riskLevel:RiskLevel; projectId?:string; budget?:number; estimatedCost?:number; successCriteria?:string[]; deadline?:Date; currentPhase?:string; metadata?:Record<string,unknown> }
export async function createObjective(db:PrismaClient,input:CreateObjectiveInput){return db.objective.create({data:{organizationId:input.organizationId,title:input.title,description:input.description,createdBy:input.createdBy,priority:input.priority,riskLevel:input.riskLevel,projectId:input.projectId,budget:input.budget,estimatedCost:input.estimatedCost,successCriteria:input.successCriteria??[],deadline:input.deadline,currentPhase:input.currentPhase,metadata:(input.metadata??{}) as any,actualCost:0}})}
export async function transitionObjective(db:PrismaClient,id:string,from:ObjectiveStatus,to:ObjectiveStatus){return db.$transaction(async tx=>{const current=await tx.objective.findUnique({where:{id}});if(!current)throw new Error(`Objective not found: ${id}`);if(current.status!==from)throw new Error(`Objective ${id} is ${current.status}; expected ${from}`);const now=new Date();return tx.objective.update({where:{id},data:{status:to,startedAt:to==='RUNNING'?now:undefined,completedAt:['COMPLETED','FAILED','CANCELLED'].includes(to)?now:undefined}})})}
export async function readTaskGraph(db:PrismaClient,objectiveId:string):Promise<TaskGraph>{const tasks=await db.task.findMany({where:{objectiveId},include:{dependencies:true},orderBy:{createdAt:'asc'}});const graph:TaskGraph={tasks:tasks.map(task=>({id:task.id,objectiveId:task.objectiveId,title:task.title,description:task.description,status:task.status as TaskStatus,dependencies:task.dependencies.map(edge=>edge.dependencyId),assignedAgentId:task.assignedAgentId??undefined,riskLevel:normalizeTaskRisk(task.riskLevel),estimatedCost:task.estimatedCost?.toNumber(),actualCost:task.actualCost.toNumber(),retryCount:task.retryCount,retryLimit:task.retryLimit,metadata:task.metadata as Record<string,unknown>}))};validateTaskGraph(graph);return graph}
function normalizeTaskRisk(risk:DbRiskLevel):'GREEN'|'YELLOW'|'RED'{return risk==='GREEN'||risk==='YELLOW'||risk==='RED'?risk:'RED'}
