import { createHash, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import type { Prisma, PrismaClient, WorkerStatus } from '@prisma/client';
import { AUDIT_EVENTS, sanitizeAuditMetadata, type AuditEventInput } from './audit.js';
const N=16384;const R=8;const P=1;const KEY_LENGTH=64;
export function createWorkerCredential(raw:string){if(typeof raw!=='string'||raw.length<24)throw new Error('Worker credential must be at least 24 characters.');const salt=randomBytes(16);const derived=scryptSync(raw,salt,KEY_LENGTH,{N,r:R,p:P});return{verifier:`scrypt-v1:${salt.toString('base64url')}:${derived.toString('base64url')}`,secret:raw};}
export function verifyWorkerCredential(raw:string,verifier:string){try{const [scheme,saltText,keyText]=verifier.split(':');if(scheme!=='scrypt-v1'||!saltText||!keyText)return false;const salt=Buffer.from(saltText,'base64url');const expected=Buffer.from(keyText,'base64url');const actual=scryptSync(raw,salt,expected.length,{N,r:R,p:P});return expected.length===actual.length&&timingSafeEqual(expected,actual);}catch{return false;}}
export function executionFingerprint(input:{action:string;target:string;parameters?:Record<string,unknown>;risk:string;environment?:string}){const canonical=JSON.stringify({action:input.action,target:input.target,parameters:sanitizeAuditMetadata(input.parameters??{}),risk:input.risk,environment:input.environment??'development'});return createHash('sha256').update(canonical).digest('hex');}
export interface CreateWorkerInput{organizationId:string;name:string;type:string;capabilities:string[];permissionProfile?:Record<string,unknown>;metadata?:Record<string,unknown>;credential:string;}
export class WorkerRepository{constructor(private readonly db:PrismaClient){}
async create(input:CreateWorkerInput,audit:AuditEventInput){const {verifier}=createWorkerCredential(input.credential);return this.db.$transaction(async tx=>{const worker=await tx.worker.create({data:{organization:{connect:{id:input.organizationId}},name:input.name,type:input.type,capabilities:sanitizeAuditMetadata(input.capabilities) as Prisma.InputJsonValue,permissionProfile:sanitizeAuditMetadata(input.permissionProfile??{}) as Prisma.InputJsonValue,metadata:sanitizeAuditMetadata(input.metadata??{}) as Prisma.InputJsonValue,credentials:{create:{verifier}}}});await tx.auditEvent.create({data:{organization:{connect:{id:input.organizationId}},actor:audit.actorId?{connect:{id:audit.actorId}}:undefined,actorType:audit.actorType,eventType:AUDIT_EVENTS.WORKER_CREATED,resourceType:'Worker',resourceId:worker.id,action:'create',result:'SUCCESS',metadata:sanitizeAuditMetadata(audit.metadata??{}) as Prisma.InputJsonValue}});return{worker,credential:input.credential};},{isolationLevel:'Serializable'});}
get(organizationId:string,id:string){return this.db.worker.findFirst({where:{organizationId,id},include:{credentials:{where:{revokedAt:null}}}})}
list(organizationId:string){return this.db.worker.findMany({where:{organizationId},orderBy:{createdAt:'asc'}})}
async authenticate(organizationId:string,workerId:string,credential:string,_audit:AuditEventInput){return this.db.$transaction(async tx=>{const worker=await tx.worker.findFirst({where:{organizationId,id:workerId},include:{credentials:{where:{revokedAt:null}}}});const valid=!!worker&&worker.status==='ACTIVE'&&worker.credentials.some(c=>(!c.expiresAt||c.expiresAt>new Date())&&verifyWorkerCredential(credential,c.verifier));if(!valid){if(worker)await tx.auditEvent.create({data:{organization:{connect:{id:organizationId}},actorType:'SYSTEM',eventType:AUDIT_EVENTS.WORKER_AUTHENTICATION_FAILED,resourceType:'Worker',resourceId:worker.id,action:'authenticate',result:'DENIED',metadata:{reason:'authentication_failed'}}});return null;}const now=new Date();await tx.worker.update({where:{id:worker.id},data:{lastActivityAt:now}});await tx.workerCredential.updateMany({where:{workerId:worker.id,revokedAt:null},data:{lastUsedAt:now}});await tx.auditEvent.create({data:{organization:{connect:{id:organizationId}},actorType:'SYSTEM',eventType:AUDIT_EVENTS.WORKER_AUTHENTICATED,resourceType:'Worker',resourceId:worker.id,action:'authenticate',result:'SUCCESS',metadata:{credentialVerified:true}}});return worker;},{isolationLevel:'Serializable'});}
async rotateCredential(organizationId:string,workerId:string,newCredential:string,audit:AuditEventInput){const {verifier}=createWorkerCredential(newCredential);return this.db.$transaction(async tx=>{const w=await tx.worker.findFirst({where:{organizationId,id:workerId}});if(!w)return null;await tx.workerCredential.updateMany({where:{workerId,revokedAt:null},data:{revokedAt:new Date()}});const created=await tx.workerCredential.create({data:{workerId,verifier}});await tx.auditEvent.create({data:{organization:{connect:{id:organizationId}},actor:audit.actorId?{connect:{id:audit.actorId}}:undefined,actorType:audit.actorType,eventType:AUDIT_EVENTS.WORKER_AUTHENTICATED,resourceType:'WorkerCredential',resourceId:created.id,action:'credential_rotated',result:'SUCCESS',metadata:sanitizeAuditMetadata(audit.metadata??{}) as Prisma.InputJsonValue}});return tx.worker.findUnique({where:{id:workerId}});},{isolationLevel:'Serializable'});}
async revokeCredential(organizationId:string,workerId:string,credentialId:string,audit:AuditEventInput){return this.db.$transaction(async tx=>{const w=await tx.worker.findFirst({where:{organizationId,id:workerId}});if(!w)return null;const result=await tx.workerCredential.updateMany({where:{id:credentialId,workerId,revokedAt:null},data:{revokedAt:new Date()}});if(result.count!==1)return false;await tx.auditEvent.create({data:{organization:{connect:{id:organizationId}},actor:audit.actorId?{connect:{id:audit.actorId}}:undefined,actorType:audit.actorType,eventType:AUDIT_EVENTS.WORKER_REVOKED,resourceType:'WorkerCredential',resourceId:credentialId,action:'credential_revoke',result:'SUCCESS',metadata:sanitizeAuditMetadata(audit.metadata??{}) as Prisma.InputJsonValue}});return true;},{isolationLevel:'Serializable'});}
async setStatus(organizationId:string,workerId:string,status:WorkerStatus,audit:AuditEventInput){return this.db.$transaction(async tx=>{const w=await tx.worker.findFirst({where:{organizationId,id:workerId}});if(!w)return null;const item=await tx.worker.update({where:{id:workerId},data:{status}});const eventType=status==='SUSPENDED'?AUDIT_EVENTS.WORKER_SUSPENDED:status==='REVOKED'?AUDIT_EVENTS.WORKER_REVOKED:AUDIT_EVENTS.WORKER_AUTHENTICATED;await tx.auditEvent.create({data:{organization:{connect:{id:organizationId}},actor:audit.actorId?{connect:{id:audit.actorId}}:undefined,actorType:audit.actorType,eventType,resourceType:'Worker',resourceId:workerId,action:status.toLowerCase(),result:'SUCCESS',metadata:sanitizeAuditMetadata(audit.metadata??{}) as Prisma.InputJsonValue}});return item;},{isolationLevel:'Serializable'});}}
