import type { Prisma, PrismaClient, WorkflowStatus } from '@prisma/client';
import { canTransitionWorkflow } from '@founder-os/core';
import { AUDIT_EVENTS, sanitizeAuditMetadata, type AuditEventInput } from './audit.js';
export const WORKFLOW_TRANSITIONS: Record<WorkflowStatus, readonly WorkflowStatus[]> = { PENDING:['RUNNING','CANCELLED'], RUNNING:['WAITING_APPROVAL','PAUSED','BLOCKED','COMPLETED','FAILED','CANCELLED'], WAITING_APPROVAL:['RUNNING','PAUSED','FAILED','CANCELLED'], PAUSED:['RUNNING','CANCELLED'], BLOCKED:['RUNNING','CANCELLED'], COMPLETED:[], FAILED:['RUNNING','CANCELLED'], CANCELLED:[] };
export interface CreateWorkflowInput { organizationId:string; objectiveId?:string; currentState:string; status?:WorkflowStatus; currentTaskId?:string; currentJobId?:string; resumableState?:Record<string,unknown>; metadata?:Record<string,unknown>; }
export interface WorkflowTransitionPatch { currentState?:string; currentTaskId?:string|null; currentJobId?:string|null; resumableState?:Record<string,unknown>; metadata?:Record<string,unknown>; failureCode?:string|null; failureMessage?:string|null; }
const json=(v:unknown)=>sanitizeAuditMetadata(v) as Prisma.InputJsonValue;
export class WorkflowRepository {
 constructor(private readonly db:PrismaClient){}
 async create(input:CreateWorkflowInput,audit:AuditEventInput){return this.db.$transaction(async(tx)=>{if(input.objectiveId&&!await tx.objective.findFirst({where:{id:input.objectiveId,organizationId:input.organizationId}}))return null;if(input.currentTaskId&&!await tx.task.findFirst({where:{id:input.currentTaskId,objective:{organizationId:input.organizationId}}}))return null;if(input.currentJobId){const job=await tx.job.findFirst({where:{id:input.currentJobId,organizationId:input.organizationId}});if(!job||job.workflowId||input.objectiveId&&job.objectiveId&&job.objectiveId!==input.objectiveId||input.currentTaskId&&job.taskId&&job.taskId!==input.currentTaskId)return null;}const item=await tx.workflow.create({data:{organization:{connect:{id:input.organizationId}},objectiveId:input.objectiveId,currentState:input.currentState,status:input.status??'PENDING',currentTaskId:input.currentTaskId,currentJobId:input.currentJobId,resumableState:json(input.resumableState??{}),metadata:json(input.metadata??{})}});if(input.currentJobId)await tx.job.update({where:{id:input.currentJobId},data:{workflowId:item.id}});await tx.auditEvent.create({data:{organization:{connect:{id:input.organizationId}},actor:audit.actorId?{connect:{id:audit.actorId}}:undefined,actorType:audit.actorType,eventType:AUDIT_EVENTS.WORKFLOW_CREATED,resourceType:'Workflow',resourceId:item.id,action:audit.action,result:audit.result,metadata:json(audit.metadata??{})}});return item;},{isolationLevel:'Serializable'});}
 list(organizationId:string){return this.db.workflow.findMany({where:{organizationId},orderBy:{updatedAt:'desc'}});}
 get(organizationId:string,id:string){return this.db.workflow.findFirst({where:{organizationId,id}});}
 async transition(organizationId:string,id:string,to:WorkflowStatus,audit:AuditEventInput,now=new Date(),patch:WorkflowTransitionPatch={}){return this.db.$transaction(async tx=>{const current=await tx.workflow.findFirst({where:{organizationId,id}});if(!current)return{kind:'missing' as const};if(!canTransitionWorkflow(current.status,to))return{kind:'conflict' as const,status:current.status};const terminal=to==='COMPLETED'||to==='CANCELLED';if(terminal){await tx.job.updateMany({where:{organizationId,workflowId:id,status:{in:['QUEUED','CLAIMED','RUNNING','WAITING_APPROVAL','RETRY_QUEUED']}},data:{status:'CANCELLED',workerId:null,leaseExpiresAt:null,completedAt:now,failureCode:'WORKFLOW_TERMINAL'}});}const data:Prisma.WorkflowUpdateInput={status:to,currentState:patch.currentState??to,startedAt:to==='RUNNING'&&!current.startedAt?now:undefined,completedAt:terminal?now:to==='RUNNING'?null:undefined,currentTaskId:terminal?null:patch.currentTaskId===undefined?undefined:patch.currentTaskId,currentJobId:terminal?null:patch.currentJobId===undefined?undefined:patch.currentJobId,resumableState:patch.resumableState===undefined?undefined:json(patch.resumableState),metadata:patch.metadata===undefined?undefined:json(patch.metadata),failureCode:to==='RUNNING'&&patch.failureCode===undefined?null:patch.failureCode===undefined?undefined:patch.failureCode,failureMessage:to==='RUNNING'&&patch.failureMessage===undefined?null:patch.failureMessage===undefined?undefined:patch.failureMessage,retryCount:to==='RUNNING'&&current.status==='FAILED'?{increment:1}:undefined};const updated=await tx.workflow.update({where:{id},data});await tx.auditEvent.create({data:{organization:{connect:{id:organizationId}},actor:audit.actorId?{connect:{id:audit.actorId}}:undefined,actorType:audit.actorType,eventType:to==='RUNNING'&&current.status!=='PENDING'?AUDIT_EVENTS.WORKFLOW_RESUMED:to==='RUNNING'?AUDIT_EVENTS.WORKFLOW_STARTED:AUDIT_EVENTS.WORKFLOW_UPDATED,resourceType:'Workflow',resourceId:id,action:audit.action,result:audit.result,metadata:json(audit.metadata??{})}});return{kind:'updated' as const,item:updated};},{isolationLevel:'Serializable'});}
 async update(organizationId:string,id:string,data:Prisma.WorkflowUpdateInput,audit:AuditEventInput){return this.db.$transaction(async(tx)=>{if(data.status!==undefined)return null;const current=await tx.workflow.findFirst({where:{organizationId,id}});if(!current)return null;const result=await tx.workflow.updateMany({where:{organizationId,id},data:data as never});if(result.count!==1)return null;await tx.auditEvent.create({data:{organization:{connect:{id:organizationId}},actor:audit.actorId?{connect:{id:audit.actorId}}:undefined,actorType:audit.actorType,eventType:AUDIT_EVENTS.WORKFLOW_UPDATED,resourceType:'Workflow',resourceId:id,action:audit.action,result:audit.result,metadata:json(audit.metadata??{})}});return tx.workflow.findFirst({where:{organizationId,id}});},{isolationLevel:'Serializable'});}
}
