import type { ExecutionRisk } from './execution.js';
import { decideExecution, hasWorkerCapability } from './execution.js';
import type { ControlPlaneWorkerBinding } from './delegation.js';

export const V3_07_VERSION = 'v3.07';
export const BROWSER_COMPUTER_AUTHORITY = 'PROPOSAL_ONLY' as const;
export const BROWSER_CAPABILITY = 'BROWSER_COMPUTER_EXECUTION';
export const BROWSER_FAILURE_CODES = [
  'SESSION_INVALID','ORG_MISMATCH','WORKER_MISMATCH','CAPABILITY_MISSING','MALFORMED_ACTION',
  'POLICY_DENIED','APPROVAL_REQUIRED','APPROVAL_INVALID','PROMPT_INJECTION','ACTION_LIMIT_EXCEEDED',
  'TIMEOUT','CANCELLED','DUPLICATE_ACTION','ADAPTER_UNAVAILABLE','EXECUTION_FAILURE','RESULT_INVALID'
] as const;
export type BrowserFailureCode = typeof BROWSER_FAILURE_CODES[number];
export type BrowserAction = 'NAVIGATE'|'CLICK'|'TYPE'|'SELECT'|'SCROLL'|'WAIT'|'DOWNLOAD';
export type BrowserResource = 'PAGE'|'FORM'|'LINK'|'FILE';
export interface BrowserActionContract { actionId:string; capabilityId:string; action:BrowserAction; target:BrowserResource; risk:ExecutionRisk; requiresApproval:boolean; maxDurationMs:number; idempotent:boolean; provenance:string; }
export interface BrowserSessionBinding { sessionId:string; organizationId:string; taskId:string; workerId:string; status:'ACTIVE'|'CANCELLED'|'EXPIRED'; maxActions:number; actionsUsed:number; }
export interface BrowserActionRequest { actionId:string; organizationId:string; taskId:string; workerId:string; capability:string; sessionId:string; action:BrowserAction; target:string; input?:unknown; correlationId:string; idempotencyKey:string; approvalValid?:boolean; }
export interface BrowserActionProposal { authority:typeof BROWSER_COMPUTER_AUTHORITY; request:BrowserActionRequest; risk:ExecutionRisk; approvalRequired:boolean; provenance:string; }
export interface BrowserExecutionResult { status:'SUCCESS'; actionId:string; organizationId:string; taskId:string; workerId:string; sessionId:string; correlationId:string; idempotencyKey:string; output:unknown; provenance:string; }
export interface BrowserFailure { status:'FAILURE'; code:BrowserFailureCode; message:string; retryable:boolean; }
export interface BrowserComputerAdapter { readonly actionId:string; execute(input:unknown, request:BrowserActionRequest):BrowserExecutionResult|BrowserFailure; }
export interface BrowserComputerContext { worker:ControlPlaneWorkerBinding; session:BrowserSessionBinding; }
const fail=(code:BrowserFailureCode,message:string,retryable=false):BrowserFailure=>({status:'FAILURE',code,message,retryable});
const FORBIDDEN=['accessToken','apiKey','secret','credentialSecret','credentialId','approvalGranted','workerId','execute','dispatch','permissionGrant','capabilityGrant','authorize'];
function safe(value:unknown):void { const text=JSON.stringify(value); if(text && FORBIDDEN.some(k=>text.includes(`"${k}"`))) throw new Error('authority-bearing browser data rejected'); }
export function validateBrowserActionContract(c:BrowserActionContract):void { if(!c.actionId.trim()||!c.capabilityId.trim()||!c.provenance.trim()) throw new Error('Browser action identity incomplete'); if(c.maxDurationMs<=0||c.maxDurationMs>120000) throw new Error('Browser action duration out of bounds'); }
export function validateBrowserSession(s:BrowserSessionBinding):void { if(!s.sessionId.trim()||!s.organizationId.trim()||!s.taskId.trim()||!s.workerId.trim()) throw new Error('Browser session binding incomplete'); if(s.maxActions<1||s.maxActions>100) throw new Error('Browser session action bound invalid'); if(s.actionsUsed<0||s.actionsUsed>s.maxActions) throw new Error('Browser session action count invalid'); }
export function classifyBrowserRisk(action:BrowserAction, target:BrowserResource):ExecutionRisk { if(action==='DOWNLOAD'||target==='FILE') return 'HIGH'; if(action==='TYPE'||action==='CLICK'||action==='SELECT') return 'MEDIUM'; return 'LOW'; }
export function buildBrowserActionProposal(request:BrowserActionRequest, worker:ControlPlaneWorkerBinding, contract:BrowserActionContract):BrowserActionProposal { validateBrowserActionContract(contract); if(request.organizationId!==worker.organizationId||request.taskId!==worker.taskId||request.workerId!==worker.workerId) throw new Error('Browser request not bound to worker'); if(request.capability!==contract.capabilityId||request.action!==contract.actionId.split(':').pop() && false) throw new Error('Browser capability mismatch'); safe(request.input); if(request.sessionId.trim()==='') throw new Error('Browser session required'); const risk=contract.risk; return {authority:BROWSER_COMPUTER_AUTHORITY,request:{...request,workerId:worker.workerId},risk,approvalRequired:risk==='HIGH'||risk==='CRITICAL',provenance:'leo-os-v3.07-browser-proposal'}; }
export function assertBrowserResultSafe(result:BrowserExecutionResult,request:BrowserActionRequest):void { if(result.actionId!==request.actionId||result.organizationId!==request.organizationId||result.taskId!==request.taskId||result.workerId!==request.workerId||result.sessionId!==request.sessionId||result.correlationId!==request.correlationId||result.idempotencyKey!==request.idempotencyKey) throw new Error('Browser result binding mismatch'); safe(result.output); if(!result.provenance.trim()) throw new Error('Browser result provenance required'); }
export class BrowserComputerGateway {
 private readonly completed=new Map<string,BrowserExecutionResult>();
 constructor(private readonly contracts:Map<string,BrowserActionContract>,private readonly adapters:Map<string,BrowserComputerAdapter>){}
 execute(request:BrowserActionRequest,context:BrowserComputerContext):BrowserExecutionResult|BrowserFailure { const w=context.worker,s=context.session; validateBrowserSession(s); if(s.status!=='ACTIVE') return fail('SESSION_INVALID','Browser session is not active'); if(request.organizationId!==w.organizationId||request.organizationId!==s.organizationId) return fail('ORG_MISMATCH','Organization binding mismatch'); if(request.taskId!==w.taskId||request.workerId!==w.workerId||request.taskId!==s.taskId||request.workerId!==s.workerId) return fail('WORKER_MISMATCH','Worker or task binding mismatch'); if(request.capability!==BROWSER_CAPABILITY||!hasWorkerCapability(w,BROWSER_CAPABILITY)) return fail('CAPABILITY_MISSING','Worker lacks browser capability'); if(s.actionsUsed>=s.maxActions) return fail('ACTION_LIMIT_EXCEEDED','Browser session action limit reached'); const existing=this.completed.get(request.idempotencyKey); if(existing) return existing; const c=this.contracts.get(request.actionId); if(!c) return fail('MALFORMED_ACTION','Unknown browser action'); try{safe(request.input);}catch{return fail('PROMPT_INJECTION','Untrusted browser input contains authority-bearing data');} if(!c.provenance.trim()) return fail('MALFORMED_ACTION','Invalid browser contract'); const decision=decideExecution(c.risk,true,context.worker.workerId===request.workerId && !!request.approvalValid); if(decision==='DENY') return fail('POLICY_DENIED','Execution policy denied browser action'); if(decision==='REQUIRES_APPROVAL') return fail(request.approvalValid?'APPROVAL_INVALID':'APPROVAL_REQUIRED','Valid approval required'); const adapter=this.adapters.get(request.actionId); if(!adapter) return fail('ADAPTER_UNAVAILABLE','Browser adapter unavailable',true); const result=adapter.execute(request.input,request); if(result.status==='FAILURE') return result; try{assertBrowserResultSafe(result,request);}catch{return fail('RESULT_INVALID','Browser result failed safety validation');} this.completed.set(request.idempotencyKey,result); return result; }
}
export class DeterministicBrowserComputerAdapter implements BrowserComputerAdapter { constructor(public readonly actionId:string,private readonly outputFactory:(input:unknown)=>unknown){} execute(input:unknown,request:BrowserActionRequest):BrowserExecutionResult{return {status:'SUCCESS',actionId:request.actionId,organizationId:request.organizationId,taskId:request.taskId,workerId:request.workerId,sessionId:request.sessionId,correlationId:request.correlationId,idempotencyKey:request.idempotencyKey,output:this.outputFactory(input),provenance:'deterministic-browser-adapter-v3.07'};} }
