import { randomUUID } from 'node:crypto';
import { requestWithProviderSet } from './v503-intelligence-gateway.js';
import { configuredProviders } from './v503-provider-runtime.js';
export type IntegrationName='openai'|'anthropic'|'google'|'slack'|'github';
export interface IntegrationConfig{enabled:boolean;configured:boolean;requiredSecrets:string[]}
export interface IntegrationRegistry{get(name:IntegrationName):IntegrationConfig;list():Record<IntegrationName,IntegrationConfig>}
const secret=(n:string)=>Boolean(process.env[n]?.trim());
export function createIntegrationRegistry():IntegrationRegistry{const c:Record<IntegrationName,IntegrationConfig>={openai:{enabled:secret('LEO_OS_OPENAI_ENABLED'),configured:secret('OPENAI_API_KEY'),requiredSecrets:['OPENAI_API_KEY']},anthropic:{enabled:secret('LEO_OS_ANTHROPIC_ENABLED'),configured:secret('ANTHROPIC_API_KEY'),requiredSecrets:['ANTHROPIC_API_KEY']},google:{enabled:secret('LEO_OS_GOOGLE_ENABLED'),configured:secret('GOOGLE_CLIENT_ID')&&secret('GOOGLE_CLIENT_SECRET'),requiredSecrets:['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','GOOGLE_REDIRECT_URI']},slack:{enabled:secret('LEO_OS_SLACK_ENABLED'),configured:secret('SLACK_CLIENT_ID')&&secret('SLACK_CLIENT_SECRET'),requiredSecrets:['SLACK_CLIENT_ID','SLACK_CLIENT_SECRET']},github:{enabled:secret('LEO_OS_GITHUB_ENABLED'),configured:secret('GITHUB_CLIENT_ID')&&secret('GITHUB_CLIENT_SECRET'),requiredSecrets:['GITHUB_CLIENT_ID','GITHUB_CLIENT_SECRET']}};return{get:n=>c[n],list:()=>structuredClone(c)}}
export function requireIntegration(r:IntegrationRegistry,n:IntegrationName){const c=r.get(n);if(!c.enabled||!c.configured)throw new Error(`Integration ${n} is not enabled and configured.`);return c}
export interface ProviderResponse<T>{provider:IntegrationName;model?:string;data:T}
export interface ModelRequest{model:string;input:string;maxTokens?:number;temperature?:number}
export interface ModelResult{text:string;raw:unknown}
export async function callOpenAI(x:ModelRequest):Promise<ProviderResponse<ModelResult>>{requireIntegration(createIntegrationRegistry(),'openai');const requestId=randomUUID();const result=await requestWithProviderSet(configuredProviders().filter(p=>p.name==='openai'),{organizationId:'system',actorId:'integration-runtime',correlationId:requestId,prompt:x.input,maxTokens:x.maxTokens??1024,providerHint:'openai'});return{provider:'openai',model:x.model,data:{text:result.content,raw:result}}}
export async function callAnthropic(x:ModelRequest):Promise<ProviderResponse<ModelResult>>{requireIntegration(createIntegrationRegistry(),'anthropic');const requestId=randomUUID();const result=await requestWithProviderSet(configuredProviders().filter(p=>p.name==='anthropic'),{organizationId:'system',actorId:'integration-runtime',correlationId:requestId,prompt:x.input,maxTokens:x.maxTokens??1024,providerHint:'anthropic'});return{provider:'anthropic',model:x.model,data:{text:result.content,raw:result}}}
export async function googleAccessToken():Promise<string>{const token=process.env.GOOGLE_ACCESS_TOKEN?.trim();if(!token)throw new Error('GOOGLE_ACCESS_TOKEN is not configured.');return token;}
export interface GovernedCapability{provider:IntegrationName;name:string;risk:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';workerEligible:boolean}
export const GOVERNED_CAPABILITIES:GovernedCapability[]=[{provider:'openai',name:'ai.reason',risk:'LOW',workerEligible:true},{provider:'anthropic',name:'ai.reason',risk:'LOW',workerEligible:true},{provider:'google',name:'gmail.read',risk:'LOW',workerEligible:true},{provider:'google',name:'gmail.send',risk:'HIGH',workerEligible:true},{provider:'google',name:'calendar.read',risk:'LOW',workerEligible:true},{provider:'google',name:'calendar.write',risk:'HIGH',workerEligible:true},{provider:'google',name:'drive.read',risk:'LOW',workerEligible:true},{provider:'google',name:'drive.write',risk:'HIGH',workerEligible:true},{provider:'slack',name:'slack.read',risk:'LOW',workerEligible:true},{provider:'slack',name:'slack.send',risk:'HIGH',workerEligible:true},{provider:'github',name:'github.read',risk:'LOW',workerEligible:true},{provider:'github',name:'github.write',risk:'HIGH',workerEligible:true},{provider:'github',name:'github.workflow',risk:'CRITICAL',workerEligible:true}];
export function governedCapabilities(provider?:IntegrationName){return GOVERNED_CAPABILITIES.filter(x=>!provider||x.provider===provider)}
