export const V3_01_VERSION = 'v3.01';
export const PROVIDER_CREDENTIAL_AUTHORITY = 'CONTROL_PLANE_AUTHORIZED_ONLY' as const;

export const PROVIDER_STATUSES = ['AVAILABLE', 'DISABLED', 'UNAVAILABLE'] as const;
export type ProviderStatus = (typeof PROVIDER_STATUSES)[number];
export const CREDENTIAL_STATUSES = ['ACTIVE', 'REVOKED', 'EXPIRED', 'DISABLED'] as const;
export type CredentialStatus = (typeof CREDENTIAL_STATUSES)[number];

export interface V3ProviderDefinition {
  providerId: string;
  organizationId: string;
  displayName: string;
  supportedModels: readonly string[];
  supportedCapabilities: readonly string[];
  status: ProviderStatus;
  policyClass: 'CORE' | 'SPECIALIST' | 'BACKUP' | 'EXPERIMENTAL' | 'UNAVAILABLE';
  provenance: string;
}
export interface CredentialReference { credentialId: string; organizationId: string; providerId: string; status: CredentialStatus; scope: string; version: number; }
export interface ProviderCallContext { organizationId: string; providerId: string; modelId: string; credentialId: string; correlationId: string; authorization: 'AUTHORIZED_WORKER'; }
export interface CredentialLease { readonly credentialId: string; readonly providerId: string; readonly secret: string; readonly expiresAt?: string; }
export interface CredentialBroker { withCredential<T>(reference: CredentialReference, context: ProviderCallContext, operation: (lease: CredentialLease) => T): T; }
export interface ProviderRequest { providerId: string; modelId: string; input: unknown; organizationId: string; correlationId: string; }
export interface ProviderResponse<T = unknown> { providerId: string; modelId: string; correlationId: string; status: 'SUCCESS'; output: T; provenance: string; }
export interface ProviderAdapter { readonly providerId: string; generate(request: ProviderRequest, credential: CredentialLease): ProviderResponse; }
export const PROVIDER_FOUNDATION_FAILURES = ['PROVIDER_NOT_FOUND','PROVIDER_DISABLED','PROVIDER_UNAVAILABLE','MODEL_NOT_SUPPORTED','CREDENTIAL_NOT_FOUND','CREDENTIAL_REVOKED','CREDENTIAL_EXPIRED','CREDENTIAL_DISABLED','CREDENTIAL_ORG_MISMATCH','CREDENTIAL_PROVIDER_MISMATCH','AUTHORIZATION_REQUIRED','ORG_MISMATCH','PROVIDER_RESPONSE_INVALID','PROVIDER_FAILURE'] as const;
export type ProviderFoundationFailureCode = (typeof PROVIDER_FOUNDATION_FAILURES)[number];
export interface ProviderFoundationFailure { code: ProviderFoundationFailureCode; message: string; retryable: boolean; }
export type ProviderCallResult<T = unknown> = { status: 'SUCCESS'; response: ProviderResponse<T> } | { status: 'FAILURE'; failure: ProviderFoundationFailure };
function fail(code: ProviderFoundationFailureCode, message: string, retryable = false): ProviderCallResult<never> { return { status: 'FAILURE', failure: { code, message, retryable } }; }
function validateContext(context: ProviderCallContext): ProviderFoundationFailure | undefined { if (!context.organizationId.trim() || !context.providerId.trim() || !context.modelId.trim() || !context.credentialId.trim() || !context.correlationId.trim()) return { code: 'AUTHORIZATION_REQUIRED', message: 'Provider call context is incomplete', retryable: false }; if (context.authorization !== 'AUTHORIZED_WORKER') return { code: 'AUTHORIZATION_REQUIRED', message: 'Provider calls require an existing authorized worker context', retryable: false }; return undefined; }
function validateProviderResponse(response: ProviderResponse, request: ProviderRequest): ProviderFoundationFailure | undefined { if (response.status !== 'SUCCESS' || response.providerId !== request.providerId || response.modelId !== request.modelId || response.correlationId !== request.correlationId || !response.provenance) return { code: 'PROVIDER_RESPONSE_INVALID', message: 'Provider response failed provenance validation', retryable: false }; return undefined; }
export class ProviderRegistry { private readonly providers = new Map<string, V3ProviderDefinition>(); private readonly adapters = new Map<string, ProviderAdapter>(); constructor(definitions: readonly V3ProviderDefinition[], adapters: readonly ProviderAdapter[] = []) { for (const definition of definitions) { if (!definition.providerId || !definition.organizationId || !definition.provenance) throw new Error('Provider definition identity is incomplete'); if (this.providers.has(definition.providerId)) throw new Error(`Duplicate provider: ${definition.providerId}`); this.providers.set(definition.providerId, { ...definition, supportedModels: [...definition.supportedModels], supportedCapabilities: [...definition.supportedCapabilities] }); } for (const adapter of adapters) { if (this.adapters.has(adapter.providerId)) throw new Error(`Duplicate provider adapter: ${adapter.providerId}`); this.adapters.set(adapter.providerId, adapter); } } get(providerId: string): V3ProviderDefinition | undefined { return this.providers.get(providerId); } adapterFor(providerId: string): ProviderAdapter | undefined { return this.adapters.get(providerId); } }
export class ProviderGateway { constructor(private readonly registry: ProviderRegistry, private readonly credentialBroker: CredentialBroker, private readonly credentials: readonly CredentialReference[]) {} call<T = unknown>(context: ProviderCallContext, input: unknown): ProviderCallResult<T> { const contextFailure = validateContext(context); if (contextFailure) return { status: 'FAILURE', failure: contextFailure }; const provider = this.registry.get(context.providerId); if (!provider) return fail('PROVIDER_NOT_FOUND', 'Provider is not registered'); if (provider.organizationId !== context.organizationId) return fail('ORG_MISMATCH', 'Provider is bound to a different organization'); if (provider.status === 'DISABLED') return fail('PROVIDER_DISABLED', 'Provider is disabled'); if (provider.status === 'UNAVAILABLE') return fail('PROVIDER_UNAVAILABLE', 'Provider is unavailable', true); if (!provider.supportedModels.includes(context.modelId)) return fail('MODEL_NOT_SUPPORTED', 'Model is not supported by the selected provider'); const reference = this.credentials.find((candidate) => candidate.credentialId === context.credentialId); if (!reference) return fail('CREDENTIAL_NOT_FOUND', 'Credential reference was not found'); if (reference.organizationId !== context.organizationId) return fail('CREDENTIAL_ORG_MISMATCH', 'Credential belongs to a different organization'); if (reference.providerId !== context.providerId) return fail('CREDENTIAL_PROVIDER_MISMATCH', 'Credential is bound to a different provider'); if (reference.status === 'REVOKED') return fail('CREDENTIAL_REVOKED', 'Credential is revoked'); if (reference.status === 'EXPIRED') return fail('CREDENTIAL_EXPIRED', 'Credential is expired'); if (reference.status === 'DISABLED') return fail('CREDENTIAL_DISABLED', 'Credential is disabled'); const adapter = this.registry.adapterFor(context.providerId); if (!adapter) return fail('PROVIDER_NOT_FOUND', 'No provider adapter is registered'); const request: ProviderRequest = { providerId: context.providerId, modelId: context.modelId, input, organizationId: context.organizationId, correlationId: context.correlationId }; try { const response = this.credentialBroker.withCredential(reference, context, (lease) => adapter.generate(request, lease)); const responseFailure = validateProviderResponse(response, request); if (responseFailure) return { status: 'FAILURE', failure: responseFailure }; return { status: 'SUCCESS', response: response as ProviderResponse<T> }; } catch (error) { return fail('PROVIDER_FAILURE', error instanceof Error ? error.message : String(error), true); } } }
export class DeterministicCredentialBroker implements CredentialBroker { constructor(private readonly secrets: ReadonlyMap<string, string>) {} withCredential<T>(reference: CredentialReference, context: ProviderCallContext, operation: (lease: CredentialLease) => T): T { if (reference.organizationId !== context.organizationId || reference.providerId !== context.providerId || reference.credentialId !== context.credentialId) throw new Error('Credential binding mismatch'); const secret = this.secrets.get(reference.credentialId); if (secret === undefined) throw new Error('Credential secret unavailable'); return operation({ credentialId: reference.credentialId, providerId: reference.providerId, secret }); } }
