export const V503_VERSION='5.03';
export interface IntelligenceRequest{organizationId:string;actorId:string;objectiveId?:string;correlationId:string;prompt:string;maxTokens:number;providerHint?:string}
export interface IntelligenceProposal{proposalId:string;provider:string;content:string;confidence:number;correlationId:string;provenance:{requestId:string;policyVersion:string;createdAt:string};usage?:{inputTokens?:number;outputTokens?:number}}
export interface IntelligenceProvider{readonly name:string;propose(r:IntelligenceRequest):Promise<IntelligenceProposal>}
export interface IntelligencePolicy{policyVersion?:string;maxPromptChars?:number;maxTokens?:number;allowedProviders?:readonly string[];consumeQuota?:(request:IntelligenceRequest)=>void|Promise<void>}
const DEFAULT_POLICY={policyVersion:'V5.03-gateway-2',maxPromptChars:100_000,maxTokens:16_384};
export function validateIntelligenceRequest(r:IntelligenceRequest,policy:IntelligencePolicy={}):void{const p={...DEFAULT_POLICY,...policy};if(!r.organizationId||!r.actorId||!r.correlationId||!r.prompt.trim())throw new Error('invalid intelligence request');if(r.prompt.length>p.maxPromptChars)throw new Error('intelligence prompt exceeds policy limit');if(!Number.isInteger(r.maxTokens)||r.maxTokens<1||r.maxTokens>p.maxTokens)throw new Error('intelligence token budget exceeds policy limit');if(r.providerHint&&policy.allowedProviders&&!policy.allowedProviders.includes(r.providerHint))throw new Error('requested intelligence provider is not allowed')}
async function executeProvider(p:IntelligenceProvider,r:IntelligenceRequest,policy:IntelligencePolicy):Promise<IntelligenceProposal>{if(policy.allowedProviders&&!policy.allowedProviders.includes(p.name))throw new Error('intelligence provider is not allowed');const x=await p.propose(r);if(x.correlationId!==r.correlationId||!x.provenance?.requestId||x.provider!==p.name)throw new Error('invalid intelligence provenance');return Object.freeze(structuredClone(x))}
export async function requestIntelligence(p:IntelligenceProvider,r:IntelligenceRequest,policy:IntelligencePolicy={}):Promise<IntelligenceProposal>{validateIntelligenceRequest(r,policy);if(policy.consumeQuota)await policy.consumeQuota(r);return executeProvider(p,r,policy)}
export async function requestWithProviderSet(providers:readonly IntelligenceProvider[],r:IntelligenceRequest,policy:IntelligencePolicy={}):Promise<IntelligenceProposal>{validateIntelligenceRequest(r,policy);const selected=r.providerHint?providers.filter(p=>p.name===r.providerHint):providers.filter(p=>!policy.allowedProviders||policy.allowedProviders.includes(p.name));if(!selected.length)throw new Error('requested intelligence provider is unavailable');if(policy.consumeQuota)await policy.consumeQuota(r);let last:unknown;for(const provider of selected){try{return await executeProvider(provider,r,policy)}catch(error){last=error}}throw last instanceof Error?last:new Error('all intelligence providers failed')}
