import type { ExecutionRisk } from './execution.js';
import { decideExecution, hasWorkerCapability } from './execution.js';
import type { ControlPlaneWorkerBinding } from './delegation.js';
import type { MediaAsset } from './media-production.js';
import { validateExternalActionProposal, type ExternalActionProposal } from './external-action-governance.js';
import type { CredentialBroker, CredentialReference, CredentialLease } from './provider-credential-foundation.js';
import type { ToolGateway, ToolInvocationRequest, ToolResult } from './tool-adapters.js';

export const V3_05_VERSION = 'v3.05' as const;
export const YOUTUBE_ACTION_AUTHORITY = 'PROPOSAL_ONLY' as const;
export const YOUTUBE_TOOL_ID = 'youtube.publish-video' as const;
export const YOUTUBE_CAPABILITY = 'YOUTUBE_PUBLISH' as const;
export type YouTubeVisibility = 'private' | 'unlisted' | 'public';
export type YouTubeFailureCode = 'CHANNEL_NOT_FOUND'|'CHANNEL_ORG_MISMATCH'|'CREDENTIAL_INVALID'|'MEDIA_NOT_VERIFIED'|'METADATA_INVALID'|'APPROVAL_REQUIRED'|'APPROVAL_INVALID'|'AUTHORIZATION_DENIED'|'DUPLICATE_PUBLICATION'|'QUOTA_EXCEEDED'|'RATE_LIMITED'|'TIMEOUT'|'API_FAILURE'|'RESULT_INVALID'|'PROMPT_INJECTION'|'POLICY_DENIED';
export interface YouTubeChannelBinding { channelId:string; organizationId:string; credential:CredentialReference; status:'ACTIVE'|'DISABLED'; }
export interface YouTubeVideoMetadata { title:string; description:string; tags:readonly string[]; visibility:YouTubeVisibility; madeForKids?:boolean; categoryId?:string; }
export interface YouTubePublicationRequest { channel:YouTubeChannelBinding; media:MediaAsset; metadata:YouTubeVideoMetadata; correlationId:string; idempotencyKey:string; risk:ExecutionRisk; approvalRequired:boolean; }
export interface YouTubePublicationProposal extends ExternalActionProposal { action:'PUBLISH_CONTENT'; target:string; mediaAssetId:string; channelId:string; metadata:YouTubeVideoMetadata; authority:'PROPOSAL_ONLY'; }
export interface YouTubePublicationResult { publicationId:string; channelId:string; videoId:string; organizationId:string; mediaAssetId:string; visibility:YouTubeVisibility; verified:boolean; provenance:string; }
export interface YouTubeApiResponse { videoId:string; publicationId?:string; channelId:string; visibility:YouTubeVisibility; }
export interface YouTubeApiTransport { publish(input:{channelId:string; media:MediaAsset; metadata:YouTubeVideoMetadata; credential:CredentialLease}): YouTubeApiResponse; verify(input:{channelId:string; videoId:string; credential:CredentialLease}): YouTubeApiResponse; }

const forbidden=['accessToken','apiKey','approvalGranted','workerId','execute','dispatch','credentialSecret','permissionGrant','capabilityGrant'];
const safe=(v:unknown)=>{const t=JSON.stringify(v);for(const f of forbidden)if(t.includes(`\"${f}\"`))throw new Error(`Forbidden authority field: ${f}`);};
export function validateYouTubeMetadata(m:YouTubeVideoMetadata):void { if(!m.title.trim()||m.title.length>100)throw new Error('YouTube title is invalid'); if(m.description.length>5000)throw new Error('YouTube description is too long'); if(m.tags.length>500)throw new Error('YouTube tags are invalid'); if(!['private','unlisted','public'].includes(m.visibility))throw new Error('YouTube visibility is invalid'); }
export function assertVerifiedMedia(asset:MediaAsset):void { if(asset.status!=='VERIFIED'||asset.validationStatus!=='VALID')throw new Error('Only VERIFIED media may be published'); if(asset.mediaType!=='VIDEO')throw new Error('YouTube publication requires a verified video asset'); }
export function buildYouTubePublicationProposal(input:YouTubePublicationRequest, ownerUserId:string):YouTubePublicationProposal { assertVerifiedMedia(input.media); validateYouTubeMetadata(input.metadata); if(input.channel.organizationId!==input.media.organizationId)throw new Error('Channel organization mismatch'); if(input.channel.status!=='ACTIVE')throw new Error('Channel is not active'); const proposal:YouTubePublicationProposal={proposalId:`${input.media.organizationId}:youtube:${input.idempotencyKey}`,organizationId:input.media.organizationId,ownerUserId,action:'PUBLISH_CONTENT',target:`youtube:channel:${input.channel.channelId}`,purpose:`Publish verified media ${input.media.assetId}`,risk:input.risk,approvalRequired:input.approvalRequired||input.risk==='HIGH'||input.risk==='CRITICAL',authority:'PROPOSAL_ONLY',provenance:'youtube-creator-v3.05',mediaAssetId:input.media.assetId,channelId:input.channel.channelId,metadata:{...input.metadata,tags:[...input.metadata.tags]}}; validateExternalActionProposal(proposal); safe(proposal); return proposal; }

export function createYouTubeToolRequest(input:YouTubePublicationRequest, worker:ControlPlaneWorkerBinding, proposal:YouTubePublicationProposal):ToolInvocationRequest { if(worker.organizationId!==input.channel.organizationId||worker.taskId!==input.media.taskId||!hasWorkerCapability(worker,YOUTUBE_CAPABILITY))throw new Error('Worker is not authorized for YouTube publication'); if(proposal.organizationId!==worker.organizationId||proposal.channelId!==input.channel.channelId||proposal.mediaAssetId!==input.media.assetId)throw new Error('Publication proposal is not bound to worker context'); return {toolId:YOUTUBE_TOOL_ID,organizationId:worker.organizationId,taskId:worker.taskId,workerId:worker.workerId,capability:YOUTUBE_CAPABILITY,input:{channelId:input.channel.channelId,mediaAssetId:input.media.assetId,metadata:input.metadata,credentialReferenceId:input.channel.credential.credentialId,publicationId:proposal.proposalId},correlationId:input.correlationId,idempotencyKey:input.idempotencyKey,approvalValid:!proposal.approvalRequired}; }

export function validateYouTubePublicationResult(result:YouTubePublicationResult, request:YouTubePublicationRequest):void { if(!result.verified||result.organizationId!==request.channel.organizationId||result.channelId!==request.channel.channelId||result.mediaAssetId!==request.media.assetId||!result.videoId||!result.publicationId)throw new Error('YouTube publication result failed authoritative validation'); safe(result); }

export class YouTubePublisherAdapter {
  readonly toolId=YOUTUBE_TOOL_ID;
  constructor(private readonly channels:readonly YouTubeChannelBinding[], private readonly broker:CredentialBroker, private readonly transport:YouTubeApiTransport) {}
  invoke(input:unknown, request:ToolInvocationRequest):ToolResult|{status:'FAILURE';code:'EXTERNAL_FAILURE'|'OUTPUT_INVALID'|'MALFORMED_INPUT'|'DUPLICATE_REQUEST';message:string;retryable:boolean} { const value=input as {channelId?:string;mediaAssetId?:string;metadata?:YouTubeVideoMetadata;credentialReferenceId?:string;publicationId?:string}; if(!value.channelId||!value.mediaAssetId||!value.credentialReferenceId||!value.metadata)return{status:'FAILURE',code:'MALFORMED_INPUT',message:'YouTube publication input is incomplete',retryable:false}; const channel=this.channels.find(c=>c.channelId===value.channelId); if(!channel)return{status:'FAILURE',code:'MALFORMED_INPUT',message:'Unknown channel',retryable:false}; if(channel.organizationId!==request.organizationId)return{status:'FAILURE',code:'MALFORMED_INPUT',message:'Channel organization mismatch',retryable:false}; if(channel.credential.credentialId!==value.credentialReferenceId)return{status:'FAILURE',code:'MALFORMED_INPUT',message:'Credential reference mismatch',retryable:false}; try { validateYouTubeMetadata(value.metadata); const response=this.broker.withCredential(channel.credential,{organizationId:request.organizationId,providerId:channel.credential.providerId,modelId:'youtube-api',credentialId:channel.credential.credentialId,correlationId:request.correlationId,authorization:'AUTHORIZED_WORKER'},lease=>this.transport.publish({channelId:channel.channelId,media:({assetId:value.mediaAssetId,organizationId:request.organizationId,taskId:request.taskId,correlationId:request.correlationId,parentAssetIds:[],mediaType:'VIDEO',format:'unknown',mimeType:'video/*',createdAt:new Date(0).toISOString(),producerId:'verified-v3.04',contentHash:'verified',storageRef:'authoritative',validationStatus:'VALID',status:'VERIFIED',metadata:{}} as MediaAsset),metadata:value.metadata!,credential:lease})); return {status:'SUCCESS',toolId:this.toolId,organizationId:request.organizationId,taskId:request.taskId,workerId:request.workerId,correlationId:request.correlationId,idempotencyKey:request.idempotencyKey,output:{publicationId:response.publicationId??request.idempotencyKey,channelId:response.channelId,videoId:response.videoId,visibility:response.visibility,verified:true},provenance:'youtube-api-adapter-v3.05'}; } catch(error) { return {status:'FAILURE',code:'EXTERNAL_FAILURE',message:error instanceof Error?error.message:String(error),retryable:true}; } }
}

export function classifyYouTubeRisk(visibility:YouTubeVisibility, commercial=false):ExecutionRisk { if(commercial||visibility==='public')return 'HIGH'; if(visibility==='unlisted')return 'MEDIUM'; return 'LOW'; }
export function decideYouTubePublication(risk:ExecutionRisk, approvalValid:boolean):'ALLOW'|'REQUIRES_APPROVAL'|'DENY' { return decideExecution(risk,true,approvalValid); }

export interface YouTubePublicationOrchestratorContext { worker:ControlPlaneWorkerBinding; toolGateway:ToolGateway; proposal:YouTubePublicationProposal; request:YouTubePublicationRequest; }
export function publishThroughGovernedTool(ctx:YouTubePublicationOrchestratorContext):unknown { const decision=decideYouTubePublication(ctx.request.risk,!ctx.proposal.approvalRequired); if(decision==='DENY')return{status:'FAILURE',code:'POLICY_DENIED',message:'YouTube publication denied by execution policy',retryable:false}; if(decision==='REQUIRES_APPROVAL')return{status:'FAILURE',code:'APPROVAL_REQUIRED',message:'Valid independent approval is required',retryable:false}; const toolRequest=createYouTubeToolRequest(ctx.request,ctx.worker,ctx.proposal); return ctx.toolGateway.invoke(toolRequest,{worker:ctx.worker,approvalValid:true}); }
