import type { PrismaClient, ApprovalStatus, RiskLevel } from '@prisma/client';
import { hasPermission, type Permission, type Role } from '@founder-os/core';
import { ApprovalRepository, executionFingerprint, type CreateApprovalInput, AUDIT_EVENTS } from '@founder-os/db';
import { ApiError } from './errors.js';
function requirePermission(role:Role,permission:Permission){if(!hasPermission(role,permission))throw new ApiError(403,'UNAUTHORIZED','You are not authorized to perform this action.');}
export async function createApproval(db:PrismaClient,organizationId:string,requesterId:string,role:Role,input:Omit<CreateApprovalInput,'organizationId'|'requesterId'|'actionFingerprint'> & {actionFingerprint?:string}){requirePermission(role,'workflow:run');if(input.riskLevel==='RED')throw new ApiError(403,'UNAUTHORIZED','This approval requires a human-only control path.');const fingerprint=input.actionFingerprint??executionFingerprint({action:input.action,target:input.targetResourceId??'',parameters:input.evidence,risk:input.riskLevel});return new ApprovalRepository(db).create({...input,actionFingerprint:fingerprint,organizationId,requesterId},{organizationId,requesterId,actorType:'USER',eventType:AUDIT_EVENTS.APPROVAL_CREATED,action:'create',result:'SUCCESS'});}
export async function listApprovals(db:PrismaClient,organizationId:string,role:Role){requirePermission(role,'audit:read');return new ApprovalRepository(db).list(organizationId)}
export async function getApproval(db:PrismaClient,organizationId:string,id:string,role:Role){requirePermission(role,'audit:read');const item=await new ApprovalRepository(db).get(organizationId,id);if(!item)throw new ApiError(404,'NOT_FOUND','Approval not found.');return item;}
export async function decideApproval(db:PrismaClient,organizationId:string,id:string,decidingUserId:string,role:Role,next:ApprovalStatus){requirePermission(role,'approval:decide');if(!['APPROVED','REJECTED'].includes(next))throw new ApiError(422,'VALIDATION_ERROR','Invalid approval decision.');const current=await new ApprovalRepository(db).get(organizationId,id);if(!current)throw new ApiError(404,'NOT_FOUND','Approval not found.');if(current.requesterId===decidingUserId)throw new ApiError(403,'UNAUTHORIZED','A requester cannot decide their own approval.');const result=await new ApprovalRepository(db).decide(organizationId,id,next,decidingUserId,{organizationId,actorId:decidingUserId,actorType:'USER',eventType:next==='APPROVED'?AUDIT_EVENTS.APPROVAL_APPROVED:AUDIT_EVENTS.APPROVAL_REJECTED,action:next.toLowerCase(),result:'SUCCESS'});if(result.kind==='expired')throw new ApiError(409,'CONFLICT','Approval has expired.');if(result.kind==='conflict')throw new ApiError(409,'CONFLICT','Approval is no longer pending.');if(result.kind==='missing')throw new ApiError(404,'NOT_FOUND','Approval not found.');return result.item;}
export async function cancelApproval(db:PrismaClient,organizationId:string,id:string,actorId:string,role:Role){requirePermission(role,'approval:decide');const current=await new ApprovalRepository(db).get(organizationId,id);if(!current)throw new ApiError(404,'NOT_FOUND','Approval not found.');const result=await new ApprovalRepository(db).decide(organizationId,id,'CANCELLED',actorId,{organizationId,actorId,actorType:'USER',eventType:AUDIT_EVENTS.APPROVAL_CANCELLED,action:'cancel',result:'SUCCESS'});if(result.kind!=='updated')throw new ApiError(409,'CONFLICT','Approval is no longer pending.');return result.item;}
