import type { PrismaClient, ObjectiveStatus, Priority, RiskLevel, TaskStatus } from '@prisma/client';
import { INITIAL_AGENTS, analyzeTaskGraph, type TaskGraph } from '@founder-os/core';
import { ControlPlaneRepository, AUDIT_EVENTS, type DependencyTask } from '@founder-os/db';
import { ApiError } from './errors.js';
const OBJECTIVE_TRANSITIONS: Record<ObjectiveStatus, readonly ObjectiveStatus[]> = { DRAFT: ['PLANNING','CANCELLED'], PLANNING: ['READY','BLOCKED','CANCELLED'], READY: ['RUNNING','PAUSED','CANCELLED'], RUNNING: ['WAITING_APPROVAL','BLOCKED','PAUSED','COMPLETED','FAILED'], WAITING_APPROVAL: ['RUNNING','PAUSED','FAILED'], BLOCKED: ['PLANNING','PAUSED','CANCELLED'], PAUSED: ['PLANNING','READY','RUNNING','CANCELLED'], COMPLETED: [], FAILED: ['PLANNING','CANCELLED'], CANCELLED: [] };
const TASK_TRANSITIONS: Record<TaskStatus, readonly TaskStatus[]> = { PENDING: ['READY','BLOCKED','CANCELLED'], READY: ['RUNNING','CANCELLED'], RUNNING: ['WAITING_APPROVAL','BLOCKED','COMPLETED','FAILED','CANCELLED'], WAITING_APPROVAL: ['RUNNING','FAILED','CANCELLED'], BLOCKED: ['PENDING','CANCELLED'], FAILED: ['PENDING','CANCELLED'], COMPLETED: [], CANCELLED: [] };
function repo(db: PrismaClient) { return new ControlPlaneRepository(db); }
function nonEmptyString(value: unknown, field: string): string { if (typeof value !== 'string' || !value.trim() || value.length > 200) throw new ApiError(422,'VALIDATION_ERROR',`${field} must be a non-empty string.`); return value.trim(); }
function optionalString(value: unknown, field: string, max = 2000): string | undefined { if (value == null) return undefined; if (typeof value !== 'string' || value.length > max) throw new ApiError(422,'VALIDATION_ERROR',`${field} is invalid.`); return value; }
function enumValue<T extends string>(value: unknown, allowed: readonly T[], field: string): T { if (typeof value !== 'string' || !allowed.includes(value as T)) throw new ApiError(422,'VALIDATION_ERROR',`${field} is invalid.`); return value as T; }
function numberValue(value: unknown, field: string): number | undefined { if (value == null) return undefined; if (typeof value !== 'number' || !Number.isFinite(value) || value < 0) throw new ApiError(422,'VALIDATION_ERROR',`${field} must be a non-negative number.`); return value; }
const audit = (organizationId: string, actorId: string | undefined, eventType: typeof AUDIT_EVENTS[keyof typeof AUDIT_EVENTS], action: string) => ({ organizationId, actorId, actorType: 'USER' as const, eventType, action, result: 'SUCCESS' as const });
export async function listObjectives(db: PrismaClient, organizationId: string) { return repo(db).listObjectives(organizationId); }
export async function getObjective(db: PrismaClient, organizationId: string, id: string) { const item = await repo(db).getObjective(organizationId,id); if (!item) throw new ApiError(404,'NOT_FOUND','Objective not found.'); return item; }
export async function createObjective(db: PrismaClient, organizationId: string, userId: string, body: Record<string, unknown>) { const successCriteria = body.successCriteria; if (!Array.isArray(successCriteria) || !successCriteria.every((x) => typeof x === 'string' && x.length <= 1000)) throw new ApiError(422,'VALIDATION_ERROR','successCriteria must be an array of strings.'); const deadline = body.deadline == null ? undefined : new Date(String(body.deadline)); if (deadline && Number.isNaN(deadline.getTime())) throw new ApiError(422,'VALIDATION_ERROR','deadline is invalid.'); const metadata=body.metadata; if(metadata!==undefined&&(!metadata||typeof metadata!=='object'||Array.isArray(metadata))) throw new ApiError(422,'VALIDATION_ERROR','metadata is invalid.'); return repo(db).createObjective({ organization:{connect:{id:organizationId}}, createdBy:userId, title:nonEmptyString(body.title,'title'), description:nonEmptyString(body.description,'description'), projectId:optionalString(body.projectId,'projectId',200), priority:enumValue(body.priority ?? 'MEDIUM',['LOW','MEDIUM','HIGH','CRITICAL'] as const,'priority') as Priority, riskLevel:enumValue(body.riskLevel ?? 'GREEN',['GREEN','YELLOW','RED'] as const,'riskLevel'), budget:numberValue(body.budget,'budget'), estimatedCost:numberValue(body.estimatedCost,'estimatedCost'), successCriteria, deadline, metadata:metadata??{} }, audit(organizationId,userId,AUDIT_EVENTS.OBJECTIVE_CREATED,'create')); }
export async function updateObjective(db: PrismaClient, organizationId: string, id: string, body: Record<string, unknown>, userId?: string) { await getObjective(db,organizationId,id); const data: Record<string,unknown>={}; if(body.title!==undefined)data.title=nonEmptyString(body.title,'title'); if(body.description!==undefined)data.description=nonEmptyString(body.description,'description'); if(body.projectId!==undefined)data.projectId=optionalString(body.projectId,'projectId',200)??null; if(body.priority!==undefined)data.priority=enumValue(body.priority,['LOW','MEDIUM','HIGH','CRITICAL'] as const,'priority'); if(body.riskLevel!==undefined)data.riskLevel=enumValue(body.riskLevel,['GREEN','YELLOW','RED'] as const,'riskLevel'); if(body.budget!==undefined)data.budget=numberValue(body.budget,'budget'); if(body.estimatedCost!==undefined)data.estimatedCost=numberValue(body.estimatedCost,'estimatedCost'); if(body.successCriteria!==undefined){if(!Array.isArray(body.successCriteria)||!body.successCriteria.every((x)=>typeof x==='string'&&x.length<=1000))throw new ApiError(422,'VALIDATION_ERROR','successCriteria is invalid.');data.successCriteria=body.successCriteria;} if(body.metadata!==undefined){if(!body.metadata||typeof body.metadata!=='object'||Array.isArray(body.metadata))throw new ApiError(422,'VALIDATION_ERROR','metadata is invalid.');data.metadata=body.metadata;} const item=await repo(db).updateObjective(organizationId,id,data,audit(organizationId,userId,AUDIT_EVENTS.OBJECTIVE_UPDATED,'update')); if(!item)throw new ApiError(404,'NOT_FOUND','Objective not found.'); return item; }
export async function changeObjectiveStatus(db: PrismaClient, organizationId: string, id: string, next: ObjectiveStatus, userId?: string) { const current=await repo(db).getObjectiveStatus(organizationId,id); if(!current)throw new ApiError(404,'NOT_FOUND','Objective not found.'); if(!OBJECTIVE_TRANSITIONS[current.status].includes(next))throw new ApiError(409,'CONFLICT',`Cannot change objective status from ${current.status} to ${next}.`); const ok=await repo(db).changeObjectiveStatus(organizationId,id,next,{startedAt:next==='RUNNING'?new Date():undefined,completedAt:next==='COMPLETED'?new Date():undefined},audit(organizationId,userId,AUDIT_EVENTS.OBJECTIVE_STATUS_CHANGED,'status_change')); if(!ok)throw new ApiError(404,'NOT_FOUND','Objective not found.'); }
export async function deleteObjective(db: PrismaClient, organizationId: string, id: string, userId?: string) { const ok=await repo(db).deleteObjective(organizationId,id,audit(organizationId,userId,AUDIT_EVENTS.OBJECTIVE_DELETED,'delete')); if(!ok)throw new ApiError(404,'NOT_FOUND','Objective not found.'); }
async function objectiveExists(db: PrismaClient, organizationId: string, objectiveId: string){if(!(await repo(db).objectiveExists(organizationId,objectiveId)))throw new ApiError(404,'NOT_FOUND','Objective not found.');}
export async function listTasks(db: PrismaClient, organizationId: string, objectiveId: string){await objectiveExists(db,organizationId,objectiveId);return repo(db).listTasks(organizationId,objectiveId);}
export async function getTask(db: PrismaClient, organizationId: string, id: string){const item=await repo(db).getTask(organizationId,id);if(!item)throw new ApiError(404,'NOT_FOUND','Task not found.');return item;}
export async function createTask(db: PrismaClient, organizationId: string, objectiveId: string, body: Record<string, unknown>, userId?: string){const assignedAgentId=body.assignedAgentId==null?undefined:nonEmptyString(body.assignedAgentId,'assignedAgentId');if(assignedAgentId&&!INITIAL_AGENTS.some((a)=>a.id===assignedAgentId))throw new ApiError(422,'VALIDATION_ERROR','assignedAgentId is not a registered agent.');const metadata=body.metadata;if(metadata!==undefined&&(!metadata||typeof metadata!=='object'||Array.isArray(metadata)))throw new ApiError(422,'VALIDATION_ERROR','metadata is invalid.');const item=await repo(db).createTask(organizationId,objectiveId,{title:nonEmptyString(body.title,'title'),description:nonEmptyString(body.description,'description'),assignedAgentId,riskLevel:enumValue(body.riskLevel??'GREEN',['GREEN','YELLOW','RED'] as const,'riskLevel'),estimatedCost:numberValue(body.estimatedCost,'estimatedCost'),metadata:metadata??{}},audit(organizationId,userId,AUDIT_EVENTS.TASK_CREATED,'create'));if(!item)throw new ApiError(404,'NOT_FOUND','Objective not found.');return item;}
export async function updateTask(db: PrismaClient, organizationId: string, id: string, body: Record<string, unknown>, userId?: string){await getTask(db,organizationId,id);const data:Record<string,unknown>={};if(body.title!==undefined)data.title=nonEmptyString(body.title,'title');if(body.description!==undefined)data.description=nonEmptyString(body.description,'description');if(body.assignedAgentId!==undefined){const agent=body.assignedAgentId==null?undefined:nonEmptyString(body.assignedAgentId,'assignedAgentId');if(agent&&!INITIAL_AGENTS.some((a)=>a.id===agent))throw new ApiError(422,'VALIDATION_ERROR','assignedAgentId is not a registered agent.');data.assignedAgentId=agent??null;}if(body.riskLevel!==undefined)data.riskLevel=enumValue(body.riskLevel,['GREEN','YELLOW','RED'] as const,'riskLevel');if(body.estimatedCost!==undefined)data.estimatedCost=numberValue(body.estimatedCost,'estimatedCost');const item=await repo(db).updateTask(organizationId,id,data,audit(organizationId,userId,AUDIT_EVENTS.TASK_UPDATED,'update'));if(!item)throw new ApiError(404,'NOT_FOUND','Task not found.');return item;}
export async function changeTaskStatus(db: PrismaClient, organizationId: string, id: string, next: TaskStatus, userId?: string){const current=await repo(db).getTaskStatus(organizationId,id);if(!current)throw new ApiError(404,'NOT_FOUND','Task not found.');if(!TASK_TRANSITIONS[current.status].includes(next))throw new ApiError(409,'CONFLICT',`Cannot change task status from ${current.status} to ${next}.`);const ok=await repo(db).changeTaskStatus(organizationId,id,next,{startedAt:next==='RUNNING'?new Date():undefined,completedAt:next==='COMPLETED'?new Date():undefined},audit(organizationId,userId,AUDIT_EVENTS.TASK_STATUS_CHANGED,'status_change'));if(!ok)throw new ApiError(404,'NOT_FOUND','Task not found.');}
export async function deleteTask(db: PrismaClient, organizationId: string, id: string, userId?: string){const ok=await repo(db).deleteTask(organizationId,id,audit(organizationId,userId,AUDIT_EVENTS.TASK_DELETED,'delete'));if(!ok)throw new ApiError(404,'NOT_FOUND','Task not found.');}
function graphFrom(tasks:DependencyTask[]):TaskGraph{return{tasks:tasks.map(t=>({id:t.id,objectiveId:t.objectiveId,title:t.title,description:t.description,status:t.status,assignedAgentId:t.assignedAgentId??undefined,riskLevel:normalizeTaskRisk(t.riskLevel),estimatedCost:t.estimatedCost==null?undefined:Number(t.estimatedCost),actualCost:Number(t.actualCost),retryCount:t.retryCount,retryLimit:t.retryLimit,metadata:(t.metadata??{}) as Record<string,unknown>,dependencies:t.dependencies.map(d=>d.dependencyId)}))};}
function normalizeTaskRisk(risk:RiskLevel):'GREEN'|'YELLOW'|'RED'{return risk==='GREEN'||risk==='YELLOW'||risk==='RED'?risk:'RED'}
export async function addDependency(db:PrismaClient,organizationId:string,taskId:string,dependencyId:string,userId?:string){if(taskId===dependencyId)throw new ApiError(422,'VALIDATION_ERROR','A task cannot depend on itself.');const result=await repo(db).addDependencyAtomic(organizationId,taskId,dependencyId,(tasks)=>{const graph=graphFrom(tasks);graph.tasks.find(t=>t.id===taskId)!.dependencies.push(dependencyId);try{analyzeTaskGraph(graph);}catch(error){throw new ApiError(409,'CONFLICT',error instanceof Error?error.message:'Invalid task dependency graph.');}},audit(organizationId,userId,AUDIT_EVENTS.TASK_DEPENDENCY_ADDED,'add'));if(result.kind==='missing')throw new ApiError(404,'NOT_FOUND','Task not found.');if(result.kind==='duplicate')throw new ApiError(409,'CONFLICT','Dependency already exists.');return result.relation;}
export async function removeDependency(db:PrismaClient,organizationId:string,taskId:string,dependencyId:string,userId?:string){const ok=await repo(db).removeDependency(organizationId,taskId,dependencyId,audit(organizationId,userId,AUDIT_EVENTS.TASK_DEPENDENCY_REMOVED,'remove'));if(!ok)throw new ApiError(404,'NOT_FOUND','Dependency not found.');}
