import { createCipheriv, createDecipheriv, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import type { IncomingHttpHeaders } from 'node:http';
import type { PrismaClient } from '@prisma/client';
import { requireOrganization } from './auth-context.js';
import { ApiError } from './errors.js';

export type OAuthProvider = 'google' | 'slack' | 'github';
const providers: Record<OAuthProvider, { label: string; description: string; scopes: string[]; auth: string; token: string; capabilities: string[] }> = {
  google: { label: 'Google Workspace', description: 'Gmail, Calendar and Drive through one governed connection.', scopes: ['openid','email','profile','https://www.googleapis.com/auth/gmail.modify','https://www.googleapis.com/auth/calendar','https://www.googleapis.com/auth/drive'], auth: 'https://accounts.google.com/o/oauth2/v2/auth', token: 'https://oauth2.googleapis.com/token', capabilities: ['gmail.read','gmail.send','calendar.read','calendar.write','drive.read','drive.write'] },
  slack: { label: 'Slack', description: 'Read permitted workspace context and send governed messages.', scopes: ['channels:read','chat:write','users:read'], auth: 'https://slack.com/oauth/v2/authorize', token: 'https://slack.com/api/oauth.v2.access', capabilities: ['slack.read','slack.send'] },
  github: { label: 'GitHub', description: 'Repositories and work items available through the control plane.', scopes: ['read:user','repo','workflow'], auth: 'https://github.com/login/oauth/authorize', token: 'https://github.com/login/oauth/access_token', capabilities: ['github.read','github.write','github.workflow'] },
};
function isProvider(value: string): value is OAuthProvider { return value in providers; }
function secretKey(): Buffer { const raw = process.env.INTEGRATION_ENCRYPTION_KEY; if (!raw) throw new ApiError(500,'INTERNAL_ERROR','Integration encryption is not configured.'); const b=Buffer.from(raw,'hex'); if(b.length!==32) throw new ApiError(500,'INTERNAL_ERROR','INTEGRATION_ENCRYPTION_KEY must be 32-byte hex.'); return b; }
function encrypt(value:string):string { const iv=randomBytes(12), c=createCipheriv('aes-256-gcm',secretKey(),iv); const body=Buffer.concat([c.update(value,'utf8'),c.final()]); return `${iv.toString('base64url')}.${c.getAuthTag().toString('base64url')}.${body.toString('base64url')}`; }
export function decrypt(value:string):string { const [iv,tag,body]=value.split('.'); if(!iv||!tag||!body) throw new Error('Invalid encrypted integration secret.'); const d=createDecipheriv('aes-256-gcm',secretKey(),Buffer.from(iv,'base64url')); d.setAuthTag(Buffer.from(tag,'base64url')); return Buffer.concat([d.update(Buffer.from(body,'base64url')),d.final()]).toString('utf8'); }
function stateSecret(){const s=process.env.SESSION_SECRET; if(!s) throw new ApiError(500,'INTERNAL_ERROR','SESSION_SECRET is not configured.'); return s;}
function signState(payload:string){return `${Buffer.from(payload).toString('base64url')}.${createHmac('sha256',stateSecret()).update(payload).digest('base64url')}`;}
function readState(value:string){const [p,s]=value.split('.'); if(!p||!s) throw new ApiError(422,'VALIDATION_ERROR','Invalid OAuth state.'); const raw=Buffer.from(p,'base64url').toString('utf8'); const expected=createHmac('sha256',stateSecret()).update(raw).digest(); const got=Buffer.from(s,'base64url'); if(got.length!==expected.length||!timingSafeEqual(got,expected)) throw new ApiError(422,'VALIDATION_ERROR','Invalid OAuth state.'); let v: unknown; try { v=JSON.parse(raw); } catch { throw new ApiError(422,'VALIDATION_ERROR','Invalid OAuth state.'); } const x=v as Record<string,unknown>; if(typeof x.userId!=='string'||typeof x.organizationId!=='string'||typeof x.provider!=='string'||!isProvider(x.provider)||typeof x.exp!=='number') throw new ApiError(422,'VALIDATION_ERROR','Invalid OAuth state.'); if(x.exp<Date.now()) throw new ApiError(422,'VALIDATION_ERROR','OAuth state expired.'); return x as {userId:string;organizationId:string;provider:OAuthProvider;exp:number};}
function header(headers:IncomingHttpHeaders,name:string){const v=headers[name];return Array.isArray(v)?v[0]:v;}
function redirectBase(){return process.env.API_PUBLIC_ORIGIN ?? `http://localhost:${process.env.PORT ?? 4000}`;}
function client(provider:OAuthProvider){const p=provider==='google'?['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET']:provider==='slack'?['SLACK_CLIENT_ID','SLACK_CLIENT_SECRET']:['GITHUB_CLIENT_ID','GITHUB_CLIENT_SECRET']; const id=process.env[p[0]],secret=process.env[p[1]]; if(!id||!secret) throw new ApiError(500,'INTERNAL_ERROR',`${providers[provider].label} OAuth is not configured.`); return {id,secret};}
export function integrationCatalog(){return Object.entries(providers).map(([id,p])=>({id,label:p.label,name:p.label,description:p.description,connectable:Boolean(process.env[id==='google'?'GOOGLE_CLIENT_ID':id==='slack'?'SLACK_CLIENT_ID':'GITHUB_CLIENT_ID']),oauth:true,scopes:p.scopes,capabilities:p.capabilities}));}
export async function startOAuth(db:PrismaClient,headers:IncomingHttpHeaders,providerInput:string){if(!isProvider(providerInput)) throw new ApiError(404,'NOT_FOUND','Integration provider not found.'); const provider=providerInput; const c=await requireOrganization(db,headers,'integration:manage'); const {id}=client(provider); const callback=`${redirectBase()}/v1/integrations/${provider}/callback`; const state=signState(JSON.stringify({userId:c.userId,organizationId:c.organizationId,provider,exp:Date.now()+10*60*1000})); const q=new URLSearchParams({client_id:id,redirect_uri:callback,response_type:'code',state,scope:providers[provider].scopes.join(' ')}); if(provider==='google'){q.set('access_type','offline');q.set('prompt','consent');} return `${providers[provider].auth}?${q}`;}
async function exchange(provider:OAuthProvider,code:string){const {id,secret}=client(provider); const redirect_uri=`${redirectBase()}/v1/integrations/${provider}/callback`; const body=new URLSearchParams({client_id:id,client_secret:secret,code,redirect_uri}); if(provider==='github') body.set('accept','json'); const r=await fetch(providers[provider].token,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',accept:'application/json'},body}); const data=await r.json() as any; if(!r.ok||data.error||!data.access_token) throw new ApiError(502,'INTERNAL_ERROR','OAuth token exchange failed.'); return data;}
async function account(provider:OAuthProvider,token:string){if(provider==='github'){const r=await fetch('https://api.github.com/user',{headers:{authorization:`Bearer ${token}`,accept:'application/vnd.github+json'}});if(!r.ok) throw new ApiError(502,'INTERNAL_ERROR','GitHub account lookup failed.');const x=await r.json() as any;return{id:String(x.id),label:x.login??x.name??'GitHub'};} if(provider==='slack'){const r=await fetch('https://slack.com/api/auth.test',{headers:{authorization:`Bearer ${token}`}});const x=await r.json() as any;if(!r.ok||!x.ok) throw new ApiError(502,'INTERNAL_ERROR','Slack account lookup failed.');return{id:x.user_id??x.team_id,label:x.team??x.user??'Slack'};} const r=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{authorization:`Bearer ${token}`}});if(!r.ok) throw new ApiError(502,'INTERNAL_ERROR','Google account lookup failed.');const x=await r.json() as any;return{id:String(x.sub),label:x.email??'Google'};}
export async function callback(db:PrismaClient,providerInput:string,query:URLSearchParams){if(!isProvider(providerInput)) throw new ApiError(404,'NOT_FOUND','Integration provider not found.'); const provider=providerInput; const code=query.get('code'); const state=query.get('state'); if(!code||!state) throw new ApiError(422,'VALIDATION_ERROR','OAuth callback is missing code or state.'); const s=readState(state); if(s.provider!==provider) throw new ApiError(422,'VALIDATION_ERROR','OAuth provider mismatch.'); const token=await exchange(provider,code); const a=await account(provider,token.access_token); const refresh=token.refresh_token?encrypt(token.refresh_token):null; const access=encrypt(token.access_token); await db.$executeRaw`INSERT INTO "ConnectedIntegration" ("id","organizationId","userId","provider","accountId","accountLabel","accessTokenEnc","refreshTokenEnc","scopes","expiresAt","createdAt","updatedAt") VALUES (${randomBytes(16).toString('hex')},${s.organizationId},${s.userId},${provider},${a.id},${a.label},${access},${refresh},${token.scope?String(token.scope).split(' '):providers[provider].scopes},${token.expires_in?new Date(Date.now()+Number(token.expires_in)*1000):null},NOW(),NOW()) ON CONFLICT ("organizationId","provider","accountId") DO UPDATE SET "userId"=EXCLUDED."userId","accountLabel"=EXCLUDED."accountLabel","accessTokenEnc"=EXCLUDED."accessTokenEnc","refreshTokenEnc"=COALESCE(EXCLUDED."refreshTokenEnc","ConnectedIntegration"."refreshTokenEnc"),"scopes"=EXCLUDED."scopes","expiresAt"=EXCLUDED."expiresAt","updatedAt"=NOW(),"revokedAt"=NULL`; return s;}
export async function listIntegrations(db:PrismaClient,headers:IncomingHttpHeaders){const c=await requireOrganization(db,headers,'integration:manage'); const rows=await db.$queryRaw<Array<{provider:string;accountId:string|null;accountLabel:string|null;scopes:string[];expiresAt:Date|null;revokedAt:Date|null}>>`SELECT "provider","accountId","accountLabel","scopes","expiresAt","revokedAt" FROM "ConnectedIntegration" WHERE "organizationId"=${c.organizationId} ORDER BY "provider","createdAt" DESC`; return rows.map(x=>({...x,connected:true}));}
export async function revokeIntegration(db:PrismaClient,headers:IncomingHttpHeaders,providerInput:string){if(!isProvider(providerInput)) throw new ApiError(404,'NOT_FOUND','Integration provider not found.'); const c=await requireOrganization(db,headers,'integration:manage'); await db.$executeRaw`UPDATE "ConnectedIntegration" SET "revokedAt"=NOW(),"updatedAt"=NOW() WHERE "organizationId"=${c.organizationId} AND "provider"=${providerInput}`;}
