import test from 'node:test';
import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
import { ApprovalRepository, WorkerRepository, executionFingerprint } from '@founder-os/db';
import { authorizeExecution, consumeExecutionApproval } from '../src/execution-gateway.js';

const db=new PrismaClient();
const marker=`v109-gateway-${Date.now()}-${Math.random().toString(36).slice(2)}`;
async function cleanup(orgId:string){await db.auditEvent.deleteMany({where:{organizationId:orgId}});await db.approval.deleteMany({where:{organizationId:orgId}});await db.job.deleteMany({where:{organizationId:orgId}});await db.workflow.deleteMany({where:{organizationId:orgId}});await db.workerCredential.deleteMany({where:{worker:{organizationId:orgId}}});await db.worker.deleteMany({where:{organizationId:orgId}});await db.organization.delete({where:{id:orgId}})}

test.after(async()=>db.$disconnect());

test('V1.09 Execution Gateway enforces capability and LOW/MEDIUM/HIGH/CRITICAL policy',async(t)=>{if(!process.env.DATABASE_URL){t.skip('DATABASE_URL is required');return}const org=await db.organization.create({data:{name:marker}});try{const wr=new WorkerRepository(db),credential='gateway-worker-credential-v109-123456789',worker=await wr.create({organizationId:org.id,name:'gateway-worker',type:'test',capabilities:['internal.execute'],credential}, {organizationId:org.id,actorType:'SYSTEM',eventType:'worker.created',action:'test',result:'SUCCESS'}),base={organizationId:org.id,workerId:worker.worker.id,action:'internal.test',target:'internal',parameters:{value:1},capability:'internal.execute',credential};const low=await authorizeExecution(db,{...base,risk:'GREEN'});assert.equal(low.decision,'ALLOW');const medium=await authorizeExecution(db,{...base,risk:'YELLOW'});assert.equal(medium.decision,'ALLOW');const deniedCapability=await authorizeExecution(db,{...base,risk:'GREEN',capability:'missing.capability'});assert.equal(deniedCapability.decision,'DENY');const job=await db.job.create({data:{organizationId:org.id,status:'RUNNING',resumableState:{},metadata:{}}});const high=await authorizeExecution(db,{...base,risk:'HIGH',jobId:job.id,expiresAt:new Date(Date.now()+60000)});assert.equal(high.decision,'REQUIRES_APPROVAL');assert.ok(high.approvalId);const approval=await new ApprovalRepository(db).get(org.id,high.approvalId!);assert.equal(approval?.jobId,job.id);assert.equal(approval?.actionFingerprint,executionFingerprint({...base,risk:'HIGH'}));const decider=await db.user.create({data:{email:`${marker}@example.test`}});assert.equal((await new ApprovalRepository(db).decide(org.id,high.approvalId!,'APPROVED',decider.id,{organizationId:org.id,actorType:'USER',action:'approve',result:'SUCCESS'})).kind,'updated');const allowed=await authorizeExecution(db,{...base,risk:'HIGH',jobId:job.id,approvalId:high.approvalId!});assert.equal(allowed.decision,'ALLOW');const consumed=await consumeExecutionApproval(db,org.id,worker.worker.id,high.approvalId!,{...base,risk:'HIGH',jobId:job.id,approvalId:high.approvalId!});assert.equal(consumed.decision,'ALLOW');await assert.rejects(()=>consumeExecutionApproval(db,org.id,worker.worker.id,high.approvalId!,{...base,risk:'HIGH',jobId:job.id,approvalId:high.approvalId!}));const critical=await authorizeExecution(db,{...base,risk:'CRITICAL'});assert.equal(critical.decision,'DENY')}finally{await cleanup(org.id)}});
