import test from 'node:test';
import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
import { JobRepository, WorkerRepository, ensureWorkflowJob } from '../src/index.js';
const db=new PrismaClient();const marker=`v108-${Date.now()}-${Math.random().toString(36).slice(2)}`;
async function cleanup(orgId:string){await db.auditEvent.deleteMany({where:{organizationId:orgId}});await db.checkpoint.deleteMany({where:{organizationId:orgId}});await db.job.deleteMany({where:{organizationId:orgId}});await db.workflow.deleteMany({where:{organizationId:orgId}});const tasks=await db.task.findMany({where:{objective:{organizationId:orgId}},select:{id:true}});for(const t of tasks)await db.taskDependency.deleteMany({where:{OR:[{taskId:t.id},{dependencyId:t.id}]}});await db.task.deleteMany({where:{objective:{organizationId:orgId}}});await db.objective.deleteMany({where:{organizationId:orgId}});await db.workerCredential.deleteMany({where:{worker:{organizationId:orgId}}});await db.worker.deleteMany({where:{organizationId:orgId}});await db.organization.delete({where:{id:orgId}})}
test.after(async()=>db.$disconnect());

test('V1.08 real DB idempotency is organization scoped',async(t)=>{if(!process.env.DATABASE_URL){t.skip('DATABASE_URL is required');return}const a=await db.organization.create({data:{name:`${marker}-a`}}),b=await db.organization.create({data:{name:`${marker}-b`}});try{const r=new JobRepository(db),key=`${marker}-same`;const one=await r.create({organizationId:a.id,idempotencyKey:key},{organizationId:a.id,actorType:'SYSTEM',eventType:'job.created',action:'test',result:'SUCCESS'});const same=await r.create({organizationId:a.id,idempotencyKey:key},{organizationId:a.id,actorType:'SYSTEM',eventType:'job.created',action:'test',result:'SUCCESS'});const other=await r.create({organizationId:b.id,idempotencyKey:key},{organizationId:b.id,actorType:'SYSTEM',eventType:'job.created',action:'test',result:'SUCCESS'});assert.equal(same?.id,one?.id);assert.notEqual(other?.id,one?.id)}finally{await cleanup(a.id);await cleanup(b.id)}});

test('V1.08 two workers cannot both claim one job',async(t)=>{if(!process.env.DATABASE_URL){t.skip('DATABASE_URL is required');return}const org=await db.organization.create({data:{name:marker}});try{const wr=new WorkerRepository(db),c1=`credential-${marker}-one-123456789`,c2=`credential-${marker}-two-123456789`,w1=await wr.create({organizationId:org.id,name:'w1',type:'test',capabilities:['internal.execute'],credential:c1},{organizationId:org.id,actorType:'SYSTEM',eventType:'worker.created',action:'test',result:'SUCCESS'}),w2=await wr.create({organizationId:org.id,name:'w2',type:'test',capabilities:['internal.execute'],credential:c2},{organizationId:org.id,actorType:'SYSTEM',eventType:'worker.created',action:'test',result:'SUCCESS'}),job=await db.job.create({data:{organizationId:org.id,idempotencyKey:`${marker}-claim`,status:'QUEUED',resumableState:{},metadata:{}}}),r=new JobRepository(db);const results=await Promise.all([r.claim(org.id,job.id,w1.worker.id,30000,{organizationId:org.id,actorType:'SYSTEM',eventType:'job.claimed',action:'race',result:'SUCCESS'}),r.claim(org.id,job.id,w2.worker.id,30000,{organizationId:org.id,actorType:'SYSTEM',eventType:'job.claimed',action:'race',result:'SUCCESS'})]);assert.equal(results.filter(x=>x.kind==='claimed').length,1)}finally{await cleanup(org.id)}});

test('V1.08 workflow bootstrap creates a non-null idempotent job',async(t)=>{if(!process.env.DATABASE_URL){t.skip('DATABASE_URL is required');return}const org=await db.organization.create({data:{name:marker}});try{const objective=await db.objective.create({data:{organizationId:org.id,title:marker,description:'runtime',createdBy:'test',priority:'MEDIUM',status:'READY',riskLevel:'GREEN',successCriteria:{ok:true},metadata:{}}}),task=await db.task.create({data:{objectiveId:objective.id,title:'one',description:'',status:'PENDING',metadata:{handlerId:'internal.noop',capability:'internal.execute',risk:'LOW',parameters:{}}}}),wf=await db.workflow.create({data:{organizationId:org.id,objectiveId:objective.id,currentState:'PENDING',status:'PENDING',metadata:{},resumableState:{}}});const r=await ensureWorkflowJob(db,org.id,wf.id,{organizationId:org.id,actorType:'SYSTEM',eventType:'workflow.task_selected',action:'test',result:'SUCCESS'});assert.equal(r.kind,'created');if(r.kind==='created'){const job=await db.job.findUnique({where:{id:r.jobId}});assert.equal(job?.idempotencyKey,`workflow:${wf.id}:task:${task.id}`);assert.equal(job?.status,'QUEUED')}}finally{await cleanup(org.id)}});
