import test from 'node:test';
import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
import { ApprovalRepository, JobRepository, WorkerRepository, cancelWorkflow } from '../src/index.js';

const db=new PrismaClient();
const marker=`v109-concurrency-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const audit=(organizationId:string,action='test')=>({organizationId,actorType:'SYSTEM' as const,eventType:'job.created' as const,action,result:'SUCCESS' as const});
async function cleanup(orgId:string){await db.auditEvent.deleteMany({where:{organizationId:orgId}});await db.approval.deleteMany({where:{organizationId:orgId}});await db.job.deleteMany({where:{organizationId:orgId}});await db.workflow.deleteMany({where:{organizationId:orgId}});await db.workerCredential.deleteMany({where:{worker:{organizationId:orgId}}});await db.worker.deleteMany({where:{organizationId:orgId}});await db.organization.delete({where:{id:orgId}})}
test.after(async()=>db.$disconnect());

test('V1.09 concurrent approval decisions serialize to one winner',async(t)=>{if(!process.env.DATABASE_URL){t.skip('DATABASE_URL is required');return}const org=await db.organization.create({data:{name:marker}});try{const requester=await db.user.create({data:{email:`${marker}-requester@example.test`}}),one=await db.user.create({data:{email:`${marker}-one@example.test`}}),two=await db.user.create({data:{email:`${marker}-two@example.test`}}),repo=new ApprovalRepository(db),approval=await repo.create({organizationId:org.id,requesterId:requester.id,action:'concurrent',actionFingerprint:'concurrent-fp',policyVersion:'v1',riskLevel:'HIGH',reason:'test',evidence:{}},{organizationId:org.id,actorType:'SYSTEM',action:'create',result:'SUCCESS'});assert.ok(approval);const results=await Promise.all([repo.decide(org.id,approval!.id,'APPROVED',one.id,{organizationId:org.id,actorType:'USER',action:'approve',result:'SUCCESS'}),repo.decide(org.id,approval!.id,'REJECTED',two.id,{organizationId:org.id,actorType:'USER',action:'reject',result:'SUCCESS'})]);assert.equal(results.filter(r=>r.kind==='updated').length,1);assert.equal(results.filter(r=>r.kind==='conflict').length,1);const stored=await repo.get(org.id,approval!.id);assert.ok(stored?.status==='APPROVED'||stored?.status==='REJECTED')}finally{await cleanup(org.id)}});

test('V1.09 concurrent approval consumption is single-use',async(t)=>{if(!process.env.DATABASE_URL){t.skip('DATABASE_URL is required');return}const org=await db.organization.create({data:{name:`${marker}-consume`}});try{const worker=await new WorkerRepository(db).create({organizationId:org.id,name:'worker',type:'test',capabilities:['internal.execute'],credential:'consume-worker-v109-123456789'},{organizationId:org.id,actorType:'SYSTEM',eventType:'worker.created',action:'create',result:'SUCCESS'}),repo=new ApprovalRepository(db),approval=await repo.create({organizationId:org.id,requesterAgentId:worker.worker.id,action:'consume',actionFingerprint:'consume-fp',policyVersion:'v1',riskLevel:'HIGH',reason:'test',evidence:{}},{organizationId:org.id,actorType:'SYSTEM',action:'create',result:'SUCCESS'});assert.ok(approval);await db.approval.update({where:{id:approval!.id},data:{status:'APPROVED'}});const results=await Promise.all([repo.consume(org.id,approval!.id,'consume-fp',worker.worker.id,{organizationId:org.id,actorType:'AGENT',eventType:'execution.approved',action:'consume',result:'SUCCESS'}),repo.consume(org.id,approval!.id,'consume-fp',worker.worker.id,{organizationId:org.id,actorType:'AGENT',eventType:'execution.approved',action:'consume',result:'SUCCESS'})]);assert.equal(results.filter(r=>r.kind==='consumed').length,1);assert.equal(results.filter(r=>r.kind==='conflict').length,1)}finally{await cleanup(org.id)}});

test('V1.09 concurrent job completion is single-winner and does not duplicate terminal mutation',async(t)=>{if(!process.env.DATABASE_URL){t.skip('DATABASE_URL is required');return}const org=await db.organization.create({data:{name:`${marker}-job`}});try{const worker=await new WorkerRepository(db).create({organizationId:org.id,name:'worker',type:'test',capabilities:['internal.execute'],credential:'completion-worker-v109-123456789'},{organizationId:org.id,actorType:'SYSTEM',eventType:'worker.created',action:'create',result:'SUCCESS'}),repo=new JobRepository(db),job=await repo.create({organizationId:org.id,resumableState:{},metadata:{}});assert.ok(job);assert.equal((await repo.claim(org.id,job!.id,worker.worker.id,30000,audit(org.id,'claim'))).kind,'claimed');assert.equal((await repo.transition(org.id,job!.id,'CLAIMED','RUNNING',worker.worker.id,audit(org.id,'start'))).kind,'updated');const results=await Promise.all([repo.transition(org.id,job!.id,'RUNNING','SUCCEEDED',worker.worker.id,audit(org.id,'complete-1')),repo.transition(org.id,job!.id,'RUNNING','SUCCEEDED',worker.worker.id,audit(org.id,'complete-2'))]);assert.equal(results.filter(r=>r.kind==='updated').length,1);assert.equal(results.filter(r=>r.kind==='conflict').length,1)}finally{await cleanup(org.id)}});

test('V1.09 concurrent workflow cancellation is deterministic',async(t)=>{if(!process.env.DATABASE_URL){t.skip('DATABASE_URL is required');return}const org=await db.organization.create({data:{name:`${marker}-workflow`}});try{const workflow=await db.workflow.create({data:{organizationId:org.id,currentState:'RUNNING',status:'RUNNING',metadata:{},resumableState:{}}}),results=await Promise.all([cancelWorkflow(db,org.id,workflow.id,{organizationId:org.id,actorType:'SYSTEM',action:'cancel-1',result:'SUCCESS'}),cancelWorkflow(db,org.id,workflow.id,{organizationId:org.id,actorType:'SYSTEM',action:'cancel-2',result:'SUCCESS'})]);assert.equal(results.filter(r=>r?.status==='CANCELLED').length,2);assert.equal((await db.workflow.findUnique({where:{id:workflow.id}}))?.status,'CANCELLED')}finally{await cleanup(org.id)}});
